- OWNERS
- README.md
- ROADMAP.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/3)
> Adds initial ROADMAP.md including a minimal Q2-2019 roadmap

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/38)
> Add Clive as Approver

- CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/42)
> Fixes a markdown formatting issue in CONTRIBUTING

- README.md
Also adding some relevant hyperlinks and other minor edits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/47)
> Making readme more descriptive

- config/default/manager_image_patch.yaml
/assign @cliveseldon 
/approve
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/54)
> Restores manager_image_patch.yaml

- README.md
- docs/README.md
- docs/control-plane.md
- docs/data-plane.md
To make the docs flowing from main readme, as well fixing some syntax/semantic things
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/69)
> Doc modifications 

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/77)
> Cleans up stale OWNERS

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/88)
> Added PR and Issue template.

- README.md
- cmd/manager/main.go
- docs/DEVELOPER_GUIDE.md
Adding some troubleshooting steps to Developer instructions
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/100)
> Developer instruction fixes

- pkg/constants/constants.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/102)
> Fixes an old reference to kubeflow-system

- Makefile
- hack/verify-golint.sh
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/126)
> Enabled go lint.

- hack/verify-golint.sh
Fixes #135 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/136)
> fix golint install message

- docs/DEVELOPER_GUIDE.md
Add a note to explain why there may be no pods. If you dont run get pods immediately it is a little disconcerting to see no output (as it makes you think your install is broken)
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/146)
> Add a note about scale to zero in the dev guide

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/174)
> Linked to working group on front page README

- tools/tf2openapi/README.md
- tools/tf2openapi/generator/generate.go
- tools/tf2openapi/types/tfmetagraph.go
- tools/tf2openapi/types/tfsavedmodel.go
- tools/tf2openapi/types/tfsignaturedef.go
- tools/tf2openapi/types/tftensor.go
**What this PR does / why we need it**: Add types for TF2OpenAPI
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/186)
> Add types for TF2OpenAPI

- python/alibiexplainer.Dockerfile
This PR adds a Dockerfile for building an image for the Seldon alibiexplainer.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/182)
> Dockerfile for the Seldon alibiexplainer

- docs/DEVELOPER_GUIDE.md
**What this PR does / why we need it**: `dep` installed via the install script gets the latest version of `dep`. If a contributor installs `dep` via `apt-get`, for example, they might push a dependency that would be removed if someone were running `dep` installed via the script: `dep` installed via `apt-get` ignores the [[prune]] section of Gopkg.toml while `dep` installed via the script does not. Also, `dep` via `apt-get` removes `pruneopts` etc (which are present when you run `dep` installed via the script), rewriting ~67% of Godep.lock, when someone tries to add a new dependency.
Fixes #
1. …
> Update dep installation in DEVELOPER_GUIDE

- docs/DEVELOPER_GUIDE.md
https://github.com/kubeflow/kfserving/issues/196
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/200)
> note on existing istio from kubeflow

- OWNERS
Add jiwang576 as a reviewer for kfserving, mainly code changes in tools/tf2openapi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/199)
> Add jiwang576 as a reviewer for kfserving.

- pkg/controller/kfservice/kfservice_controller.go
Fixes https://github.com/knative/serving/issues/4564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/202)
> fix route and configuration race

- python/pytorchserver/pytorchserver/test_model.py
- python/pytorchserver/setup.py
Got linter failures attempting to test #156 ... not sure how these got in?
@animeshsingh @ellis-bigelow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/206)
> fix pytorch pylint errors

- OWNERS
Add hougangliu as a reviewer for kfserving, mainly focus
on kfserving controller and CI test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/211)
> Add hougang as reviewer

- docs/samples/pytorch/README.md
- docs/samples/sklearn/README.md
- docs/samples/xgboost/README.md
- pkg/apis/serving/v1alpha1/kfservice_framework_pytorch.go
- pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt.go
- pkg/apis/serving/v1alpha1/kfservice_framework_tensorrt_test.go
- pkg/apis/serving/v1alpha1/kfservice_validation.go
- pkg/apis/serving/v1alpha1/kfservice_validation_test.go
- python/kfserving/README.md
- python/kfserving/kfserving/storage.py
- python/kfserving/kfserving/test_storage.py
- python/kfserving/setup.py
- python/pytorchserver/README.md
- python/sklearnserver/README.md
- python/xgbserver/README.md
replaces #172 for #168 
/assign ellis-bigelow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/212)
> adds support for anonymous azure blobs

- ROADMAP.md
Proposed ROADMAP from KFServing Working Group Meetings.
Included in scope of #170
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/173)
> Updates the Roadmap for Q2/Q3

- config/default/configmap/kfservice.yaml
- install/v0.1.0/kfserving.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/227)
> Add pytorchserver image in kfservice-config

- Gopkg.lock
- Gopkg.toml
- tools/tf2openapi/README.md
- tools/tf2openapi/cmd/main.go
**What this PR does / why we need it**: Add CLI documentation to Tf2OpenAPI
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/220)
> Tf2OpenAPI: Add CLI documentation

- ROADMAP.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/230)
> minor enhancements to roadmap

- config/default/configmap/kfservice.yaml
- install/v0.1.0/kfserving.yaml
Typo: missing comma from recent merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/231)
> Fix invalid json in configmap

- test/workflows/app.yaml
The presubmit test failed, and the problem has been work out by @karthikv2k in https://github.com/kubeflow/fairing/pull/313 in fairing, apply the fix solution for KFServing.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/239)
> work out presubmit test problem

- cmd/spec-gen/main.go
- config/default/configmap/kfservice.yaml
- config/overlays/development/kustomization.yaml
- pkg/webhook/admission/deployment/model_initializer_injector.go
- pkg/webhook/admission/deployment/model_initializer_injector_test.go
- pkg/webhook/admission/deployment/mutator.go
Currently model initializer image name and version is hard coded, moving it to configmap.
Fixes #
```release-note
Add the model initializer image name/version to kfservice config map
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/244)
> Add model initializer config

- tools/tf2openapi/README.md
- tools/tf2openapi/cmd/main.go
- tools/tf2openapi/generator/generate.go
- tools/tf2openapi/generator/tensorflow_serving_protocol.go
- tools/tf2openapi/types/tfdtype.go
- tools/tf2openapi/types/tfdtype_test.go
- tools/tf2openapi/types/tfmetagraph.go
- tools/tf2openapi/types/tfmetagraph_test.go
- tools/tf2openapi/types/tfsavedmodel.go
- tools/tf2openapi/types/tfsavedmodel_test.go
- tools/tf2openapi/types/tfsignaturedef.go
- tools/tf2openapi/types/tfsignaturedef_test.go
- tools/tf2openapi/types/tftensor.go
- tools/tf2openapi/types/tftensor_test.go
**What this PR does / why we need it**: Generate OpenAPI from internal models
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/214)
> TF2OpenAPI: Generate OpenAPI from internal models

- Gopkg.lock
- vendor/github.com/getkin/kin-openapi/openapi3filter/authentication_input.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/errors.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/internal.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/options.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/req_resp_decoder.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/router.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/validate_request.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/validate_request_input.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/validate_response.go
- vendor/github.com/getkin/kin-openapi/openapi3filter/validate_response_input.go
- vendor/github.com/getkin/kin-openapi/pathpattern/node.go
**What this PR does / why we need it**: Vendor request validator for TF2OpenAPI tests
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/257)
> Vendor request validator for TF2OpenAPI tests

- hack/generate-cloudbuild-triggers.sh
- release/triggers/tf2openapi.yaml
- tools/tf2openapi/Dockerfile
**What this PR does / why we need it**: Add TF2OpenAPI Dockerfile + CloudBuild trigger
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/262)
> TF2OpenAPI Dockerfile + CloudBuild trigger

- docs/samples/pytorch/README.md
- docs/samples/xgboost/README.md
- python/pytorchserver/README.md
- python/sklearnserver/README.md
- python/xgbserver/README.md
Today I tried the kfervice python related features and reviewed some documents, and hit some small problems. The PR is going to fix the problems. Thanks.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/267)
> fix some typos

- docs/samples/explanation/income/requirements.txt
Make explicit dependencies for training model and explainer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/266)
> add requirements.txt for explainer

- release/triggers/alibi-explainer.yaml
- release/triggers/executor.yaml
- release/triggers/kfserving-controller.yaml
- release/triggers/model-initalizer.yaml
- release/triggers/pytorch.yaml
- release/triggers/sklearnserver.yaml
- release/triggers/tf2openapi.yaml
- release/triggers/xgbserver.yaml
**What this PR does / why we need it**: Trigger CloudBuild whenever a new GitHub tag is added, regardless of what files have changed
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/274)
> Trigger CloudBuild with every new tag

- release/triggers/executor.yaml
**What this PR does / why we need it**: Fix Docker build context for Executor Cloud Build Trigger to succeed
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/275)
> Fix Docker Build Context for Executor

- pkg/apis/serving/v1alpha1/framework_custom.go
- pkg/constants/constants.go
- pkg/webhook/admission/deployment/model_initializer_injector.go
- pkg/webhook/admission/deployment/model_initializer_injector_test.go
Support for #219
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/222)
> Add model initialization for CustomSpec

- README.md
- python/kfserving/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/286)
> Minor update on SDK verbiage

- config/default/crds/serving_v1alpha2_kfservice.yaml
- docs/DEVELOPER_GUIDE.md
- docs/samples/tensorflow/README.md
- pkg/apis/serving/v1alpha2/kfservice_types.go
Add overall status for `kubectl get kfservice` cli, see details in #306 
After the PR, the `kubectl get kfservice` will be shown as following:
```
[root@jinchi1 kfserving]# kubectl get kfservice
NAME             READY     URL                                          DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample   Unknown   http://flowers-sample.kubeflow.example.com                                      43s
[root@jinchi1 kfserving]# kubectl get kfservice
NAME             READY     URL                                          DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
flowers-sample   True      http://flowers-sample.kubeflow.example.com   90                10               3m
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> add overall status for kubectl get cli

- config/default/crds/serving_v1alpha2_kfservice.yaml
- config/default/rbac/rbac_role.yaml
- pkg/apis/serving/v1alpha2/kfservice_status.go
- pkg/apis/serving/v1alpha2/kfservice_status_test.go
- pkg/constants/constants.go
- pkg/controller/kfservice/kfservice_controller.go
- pkg/controller/kfservice/kfservice_controller_test.go
- pkg/controller/kfservice/reconcilers/knative/route_reconciler.go
- pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
- pkg/controller/kfservice/reconcilers/knative/service_reconciler.go
- pkg/controller/kfservice/reconcilers/knative/service_reconciler_test.go
- pkg/controller/kfservice/resources/knative/route.go
- pkg/controller/kfservice/resources/knative/route_test.go
- pkg/controller/kfservice/resources/knative/service.go
- pkg/controller/kfservice/resources/knative/service_test.go
- pkg/utils/utils_test.go
- test/crds/knative_service.yaml
This is a step towards supporting inference endpoints for predictor, explainer and transformer, this PR converts existing predictor default/canary knative configuration to knative service since explainer and transformer needs individual routes for calling from default explainer/transformer to default predictor or canary explainer/transformer to canary predictor.
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "KFService"
metadata:
name: "flowers-sample"
spec:
default:
predictor:
tensorflow:
modelUri: "gs://kfserving-samples/models/tensorflow/flowers"
canary:
predictor:
tensorflow:
modelUri: "gs://kfserving-samples/models/tensorflow/flowers"
canaryTrafficPercent: 20
```
```
kubectl get pods
NAME …
```
> Convert predictor default/canary configurations to knative service

- pkg/constants/constants.go
- pkg/controller/kfservice/kfservice_controller_test.go
- pkg/controller/kfservice/reconcilers/knative/route_reconciler_test.go
- pkg/controller/kfservice/resources/knative/service.go
- pkg/controller/kfservice/resources/knative/service_test.go
- python/kfserving/kfserving/model.py
- python/kfserving/kfserving/protocols/request_handler.py
- python/kfserving/kfserving/protocols/seldon_http.py
- python/kfserving/kfserving/protocols/tensorflow_http.py
- python/kfserving/kfserving/server.py
- python/kfserving/kfserving/transformer.py
- python/kfserving/test/test_request_handler.py
- python/kfserving/test/test_server.py
Add transformer to control plane.
An example KFService with transformer
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "KFService"
metadata:
name: "flowers-sample"
spec:
default:
transformer:
minReplicas: 1
custom:
container:
image: "yuzisun/transformer:latest"
predictor:
tensorflow:
modelUri: "gs://kfserving-samples/models/tensorflow/flowers"
minReplicas: 1
canary:
transformer:
custom:
container:
image: "yuzisun/transformer:latest"
predictor:
tensorflow:
modelUri: "gs://kfserving-samples/models/tensorflow/flowers"
canaryTrafficPercent: 20
```
Fixes …
> Add transformer to control plane

- README.md
- docs/samples/explanation/income/train.py
- docs/samples/pipelines/sample-custom-model.py
- docs/samples/pipelines/sample-tf-pipeline.py
- docs/samples/pytorch/cifar10.py
- python/alibiexplainer/alibiexplainer/anchor_tabular.py
- python/alibiexplainer/alibiexplainer/explainer.py
- python/alibiexplainer/alibiexplainer/explainer_wrapper.py
- python/kfserving/kfserving/api_client.py
- python/kfserving/kfserving/rest.py
adding some pipelines snippet code to show kfserving usage. Will be expanded with more robus examples moving forward [added some missing license headers which caught the eye]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/340)
> curating sample pipelines to expand on

- pkg/controller/kfservice/reconcilers/knative/service_reconciler.go
- pkg/controller/kfservice/reconcilers/knative/service_reconciler_test.go
Fixes: #344
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/345)
> Fix always update knative service in reconcile thread

- Dockerfile
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/348)
> Update the Dockerfile to support ppc64le.

- docs/samples/explanation/alibi/moviesentiment/README.md
- docs/samples/explanation/alibi/moviesentiment/kfserving_text_explainer.ipynb
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/355)
> Add text explainer notebook

- release/triggers/latest/alibi-explainer.yaml
- release/triggers/latest/executor.yaml
- release/triggers/latest/kfserving-controller.yaml
- release/triggers/latest/pytorch.yaml
- release/triggers/latest/sklearnserver.yaml
- release/triggers/latest/storage-initalizer.yaml
- release/triggers/latest/tf2openapi.yaml
- release/triggers/latest/xgbserver.yaml
- release/triggers/tagged/alibi-explainer.yaml
- release/triggers/tagged/executor.yaml
- release/triggers/tagged/kfserving-controller.yaml
- release/triggers/tagged/pytorch.yaml
- release/triggers/tagged/sklearnserver.yaml
- release/triggers/tagged/storage-initalizer.yaml
- release/triggers/tagged/tf2openapi.yaml
- release/triggers/tagged/xgbserver.yaml
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/358)
> Added descriptions to cloudbuild triggers to show more cleanly in the UI

- docs/samples/transformer/image_transformer/README.md
Fix some problems in transformer example, such as duplicated description and bad link.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/364)
> Fix some problems in transformer example

- python/kfserving/kfserving/api/kf_serving_client.py
@jinchihe removed unprintable character...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/368)
> Remove  from api client

- config/default/configmap/kfservice.yaml
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/375)
> Points to KFServing's StorageInitializer image

- docs/DEVELOPER_GUIDE.md
Update troubleshooting for developers to be able to avoid a storage-initializer injection failure.
We had a discussion on the https://app.slack.com/client/T7QLHSH6U/CH6E58LNP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/377)
> Update troubleshooting to avoid a storage-initializer injection failure

- docs/DEVELOPER_GUIDE.md
To fix the description according to the https://github.com/kubeflow/kfserving/pull/377#discussion_r329293254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/378)
> Update troubleshooting to avoid a storage-initializer injection failure (take2)

- README.md
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/401)
> Tweaks README to fix typo and be more visible

- docs/samples/explanation/alibi/moviesentiment/README.md
- docs/samples/explanation/alibi/moviesentiment/moviesentiment2.yaml
- docs/samples/explanation/alibi/moviesentiment/train.py
- python/alibiexplainer/setup.py
* Provides an improved example
* Shows use of custom config to change the explanation algorithm settings for Anchor Text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/393)
> Update Alibi Anchor Text Example

- README.md
- docs/samples/pipelines/sample-tf-pipeline.py
Quick patch for pipeline sample + main README changed to reflect the website.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/409)
> Pipe patch

- docs/samples/pytorch/README.md
- docs/samples/sklearn/README.md
- docs/samples/tensorflow/README.md
- docs/samples/tensorrt/README.md
- docs/samples/transformer/image_transformer/README.md
- docs/samples/xgboost/README.md
```
http://flowers-sample.kubeflow.example.com/v1/models/flowers-sample
flowers-sample.kubeflow.example.com
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/438)
> Fix SERVICE_HOSTNAME in the example

- README.md
- docs/samples/pipelines/sample-custom-model.py
- docs/samples/pipelines/sample-tf-pipeline.py
updated to load from remote url
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/444)
> minor pipeline fixes

- docs/samples/explanation/alibi/imagenet/imagenet.yaml
- docs/samples/explanation/alibi/imagenet/test_imagenet.py
- docs/samples/explanation/alibi/income/README.md
- docs/samples/explanation/alibi/income/income.yaml
- docs/samples/explanation/alibi/moviesentiment/README.md
- docs/samples/explanation/alibi/moviesentiment/kfserving_text_explainer.ipynb
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/448)
> Fix sample wrong Host name

- pkg/controller/inferenceservice/resources/istio/virtualservice.go
Fixes: #445 
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/446)
> Explainer virtual service cannot work

- pkg/constants/constants.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/449)
> Fix hardcode k8s domain name

- pkg/controller/inferenceservice/controller.go
- pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/450)
> Fix update inferenceservice status error case

- README.md
- python/kfserving/README.md
- python/kfserving/docs/KFServingClient.md
- python/kfserving/kfserving/api/kf_serving_client.py
- test/e2e/test_tensorflow_inference_service.py
- test/e2e/utils.py
1. Update SDK docs.
2. Create a link for SDK docs in README since someone asked me how to use the KFServing SDK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/437)
> update docs related sdk

- python/alibiexplainer/alibiexplainer/anchor_tabular.py
* Fix serialization issue in Anchor tabular explanation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/443)
> Fix anchor tabular explanation serialization

- docs/samples/client/kfserving_sdk_sample.ipynb
Enhance hardcode namespace in SDK sample. see more in #429 
Fixes #429 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/457)
> Enhance hardcode namespace in SDK sample

- .gitignore
- Makefile
- config/default/configmap/inferenceservice.yaml
- hack/image_patch_dev.sh
- pkg/apis/serving/v1alpha2/configmap.go
- pkg/controller/inferenceservice/controller_test.go
- pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
- pkg/controller/inferenceservice/resources/knative/service.go
- pkg/controller/inferenceservice/resources/knative/service_test.go
- pkg/webhook/admission/pod/mutator.go
- pkg/webhook/admission/pod/storage_initializer_injector.go
- pkg/webhook/admission/pod/storage_initializer_injector_test.go
Fixes #455
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/454)
> Container resource

- docs/samples/autoscaling/README.md
- docs/samples/rollouts/pinned.yaml
- pkg/apis/serving/v1alpha2/inferenceservice_status.go
- pkg/controller/inferenceservice/controller_test.go
- pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
Fixes #460 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/461)
> One knative service to one endpoint

- docs/samples/s3/tensorflow_s3.yaml
v1alpha2 moved the service account field under predictor
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/470)
> Fix service account field on S3 example

- install/0.2.0/kfserving.yaml
Fixes #486
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/487)
> Added configmap changes

- pkg/controller/inferenceservice/resources/istio/virtualservice.go
- pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Fixes #417 
/assign @yuzisun @ellis-bigelow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/465)
> Adds virtualservice tests

- pkg/apis/serving/v1alpha2/utils.go
* Resource default Memory and CPU invalid
Fixes #511 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/510)
> Fix typo in resources

- pkg/apis/serving/v1alpha2/utils.go
- python/kfserving/kfserving/kfserver.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/512)
> Allow Tornando workers to be specified

- pkg/controller/inferenceservice/controller_test.go
Fixes #515 
tested with 
`go test -run TestCanaryDelete ./pkg/controller/inferenceservice/ -v -count 30`
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/516)
> Fix flaky test for deleting canary

- python/kfserving/kfserving/storage.py
- python/kfserving/requirements.txt
Pin to avoid breaking changes in v12 and also remove the azure package dependency
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/518)
> fix blob breaking change

- python/kfserving/kfserving/__init__.py
- python/kfserving/setup.py
For integration with fairing in https://github.com/kubeflow/fairing/pull/407, need a new pypi pkg that includes recent changes, and hit one mini problem, I just released new kfserving python pypi pkg to avoid blocking integration with fairing. thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/498)
> fix mini problem and release new pypi pkg

- test/scripts/build-custom-image-transformer.sh
- test/workflows/components/workflows.libsonnet
In the PR #525 and #524 , using the image-transformer which is in the personal repo, we should build that and push to `gcr.io/kubeflow-ci/kfserving/image-transformer`
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/526)
> Add CI step to build image-transformer

- docs/samples/transformer/image_transformer/README.md
- docs/samples/transformer/image_transformer/image_transformer.yaml
- docs/samples/transformer/image_transformer/image_transformer/__main__.py
- docs/samples/transformer/image_transformer/image_transformer/image_transformer.py
To make the sample work with the refactored kfmodel since in #492 it's refactored.
Fixes #522
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/524)
> To make the sample work with the refactored kfmodel

- README.md
- docs/DEVELOPER_GUIDE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/532)
> redirecting to common troubleshooting section

- pkg/constants/constants.go
- pkg/controller/inferenceservice/resources/knative/service.go
- pkg/controller/inferenceservice/resources/knative/service_test.go
Remove some redundant code which is confusing. 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/528)
> Remove redundant code which is confusing

- README.md
- config/default/configmap/inferenceservice.yaml
- docs/samples/transformer/image_transformer/setup.py
- hack/generate-install.sh
- install/0.2.1/kfserving.yaml
- pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go
- pkg/apis/serving/v1alpha2/inferenceservice_types.go
- pkg/apis/serving/v1alpha2/openapi_generated.go
- pkg/apis/serving/v1alpha2/swagger.json
- pkg/constants/constants.go
- python/kfserving/docs/KFServingClient.md
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/529)
> Generated 0.2.1 install

- python/pytorch.Dockerfile
Reduce pytorch image size
Fixes #535 
install `pytorch-cpu` reduces the size to 1.8G from 2.8G, we need to create a separate dockerfile for pytorch gpu image
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/536)
> Install pytorch-cpu for cpu image

- python/kfserving/kfserving/kfserver.py
Fix the log format to add more debug information
Fixes #433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/545)
> Fix the log format to add more debug information

- install/0.2.1/kfserving.yaml
Fixes #552
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/553)
> #552 Fixes a bad config for 0.2.1

- docs/samples/transformer/image_transformer/kfserving_sdk_transformer.ipynb
Change to use image from gcr
Fix the hostname to predict
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/544)
> * Change to use image from gcr

- test/e2e/utils.py
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/555)
> Fix end2end test

- test/scripts/run-e2e-tests.sh
Since the knative will be upgraded to 0.9.0, this PR is going to upgrade knative and istio as required by @animeshsingh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/559)
> upgrade istio and knative in CI tests

- ROADMAP.md
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/554)
> Roadmap changes

- docs/samples/onnx/README.md
Readme step has some issues
Fixes #565
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/566)
> Correct onnx readme steps

- release/triggers/latest/logger.yaml
- release/triggers/tagged/logger.yaml
I saw the logger is already in the configmap, but checked it's not released so we cannot use the image yet.
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/570)
> Release the logger image

- docs/README.md
Fixing few typos on the Architecture overview docs.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/588)
> Fix docs typos

- test/scripts/run-e2e-tests.sh
- test/scripts/sdk-test.sh
Recent days, the CI test failed in the sdk-test steps, the PR is going to debug and resolve the problem. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/598)
> Resovle CI SDK test problem

- docs/samples/logger/local/README.md
- pkg/logger/server.go
- pkg/logger/types.go
- pkg/logger/worker.go
* Allow the logger structs to have exported fields so the code can be used as a library by other projects
* Fix README for local logger demo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/616)
> Export LoggerRequest, Fix local logger README

- docs/samples/pipelines/README.md
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/631)
> Updated docs for KFserving pipeline to make it more clear 

- python/alibiexplainer.Dockerfile
- python/pytorch.Dockerfile
- python/sklearn.Dockerfile
- python/xgb.Dockerfile
similar to the fix for image transformer example in https://github.com/kubeflow/kfserving/pull/626, we need to apply the fix in pytorchserver also.
Fixes #635 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/636)
> Pin pillow for pytorchserver

- hack/generate-licenses.sh
- third_party/library/license.txt
- third_party/library/license_go.txt
- third_party/library/license_python.txt
Fixes #640
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/646)
> Added licenses.

- Makefile
- config/default/kustomization.yaml
- docs/DEVELOPER_GUIDE.md
- hack/self-signed-ca.sh
Add a self-signed ca script for development without cert-manager.
Fixes #642
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/650)
> Add self-signed ca script for development

- docs/samples/accelerators/README.md
```
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/stable/nvidia-driver-installer/cos/daemonset-preloaded.yaml
error: error validating "https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/stable/nvidia-driver-installer/cos/daemonset-preloaded.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
So, I went to the repo and found the latest one that worked and found the exact commit.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> Fix selector error

- README.md
- docs/DEVELOPER_GUIDE.md
- docs/samples/README.md
- hack/quick_install.sh
Fixes #602 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/656)
> Improve KFServing main README

- python/kfserving/kfserving/kfserver.py
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/665)
> Set max_buffer_size to tornado

- OWNERS
Would you please add me as reviewer? 
Now some PR about validation, logger, testing and development story enhancement... And would like to do more.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/661)
> Add pugangxa as reviewer

- test/workflows/components/workflows.libsonnet
Pin test-worker to avoid CI test failure below
```
File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
from urllib3.contrib import pyopenssl
File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
import OpenSSL.SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```
Related with https://github.com/kubeflow/testing/issues/607
1. Please confirm that if this PR …
> Pin test-worker to avoid CI test failure

- docs/DEVELOPER_GUIDE.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/670)
> Remove knctl as cli since its deprecated

- docs/samples/README.md
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/676)
> Fix examples links

- README.md
Based on feedback from some internal users
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/672)
> Rearrange and simply Installation/Testing flow

- docs/DEVELOPER_GUIDE.md
Moving the common problem of stale webhooks to the top, and adding other manifestations and troubleshooting steps for that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/680)
> Stale Webhooks Issue

- README.md
- docs/DEVELOPER_GUIDE.md
There are quite a few open issues due to unclear documentation and instructions regarding KFServing pod mutator webhook installation.
Fixes #688 #689 #685 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/692)
> Clarify KFServing pod mutator webhook installation requirement

- python/kfserving/kfserving/handlers/http.py
Relax data plane "instances" key validation so that transformer can work with onnx, trtis which are using a different data plane than KFServing, this is also going to change in v2 data plane so there is not much value doing the validation here.
Fixes #695 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserv …
> Relax data plane "instances" key validation

- hack/quick_install.sh
Install KFServing from release yaml instead of building from scratch to avoid unnecessary setup or dependency for quick install.
Fixes #702 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/714)
> Fix quick install to install from release yaml

- docs/README.md
- docs/predict-api/v2/README.md
- docs/predict-api/v2/required_api.md
Predict Protocol V2 proposal.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/709)
> Predict protocol V2 proposal

- .gitignore
- Makefile
- config/overlays/development/kustomization.yaml
- pkg/constants/constants.go
- pkg/controller/inferenceservice/controller_test.go
- pkg/controller/inferenceservice/resources/istio/virtualservice.go
- pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
**What this PR does / why we need it**: 
Make InferenceService support https
Fixes #722 
```release-note
Enable https support for inferenceservice
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/726)
> Support https

- README.md
completing the list of items for 0.3 as listed here by pointing to intial results. At some point, I will start moving them to KFServing repo itself when there is a general summarization
https://github.com/kubeflow/kfserving/issues/648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/724)
> Point to performance tests

- config/default/configmap/inferenceservice.yaml
- install/v0.3.0/kfserving.yaml
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/728)
> Fixes 0.3.0 to v0.3.0

- release/triggers/tagged/pytorch-gpu.yaml
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/729)
> Fix pytorch gpu image tag for the image build trigger

- release/triggers/tagged/pytorch-gpu.yaml
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/732)
> Fixes a missing tag in the pytorch gpu cloud builder

- ROADMAP.md
Signed-off-by: Ce Gao <gaoce@caicloud.io>
Fixes #
```release-note
```
> fix(roadmap): Fix the date typo

- docs/predict-api/v2/required_api.md
…REST
Included by mistake from an earlier revision of the proposal.
The GRPC API is alredy correct in this regard.
Also update comment on GRPC requested output tensors to align with
HTTP.
Fixes #
```release-note
```
> Model name should be included in the inference response for GRPC

- docs/DEVELOPER_GUIDE.md
- docs/samples/explanation/alibi/imagenet/README.md
Fixes #734
```release-note
```
> Add trouble shooting for IngressNotConfigured error

- python/kfserving/kfserving/api/kf_serving_client.py
The SDK `promote` method is missing current isvc's annotation
Fixes #775
```release-note
```
> fix-775 fix sdk promote missing annotations

- docs/predict-api/v2/README.md
> Add pointers to GRPC proto specification and Triton extensions

- docs/samples/kafka/README.md
- docs/samples/kafka/kafka-source.yaml
Fix stale links on kafka event source examples
Fixes #785 
```release-note
```
> Fix stale links for kafka event source example

- docs/README.md
- pkg/apis/serving/v1alpha2/transformer.go
- pkg/constants/constants.go
- pkg/controller/inferenceservice/controller_test.go
- pkg/controller/inferenceservice/resources/istio/virtualservice.go
- pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
We should not assume service name is same as the model name, this is also important when we want to support model sharing, so user can predict on a given model which is specified on the endpoint path.
Fixes #664 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/667)
> Relax top level virtual service to allow multiple model names

- docs/samples/autoscaling/README.md
- docs/samples/custom-domain/README.md
- docs/samples/custom/hello-world/README.md
- docs/samples/custom/kfserving-custom-model/README.md
- docs/samples/custom/kfserving-custom-model/kfserving_sdk_custom_image.ipynb
- docs/samples/custom/prebuilt-image/README.md
- docs/samples/explanation/alibi/imagenet/README.md
- docs/samples/explanation/alibi/income/README.md
- docs/samples/explanation/alibi/moviesentiment/README.md
- docs/samples/logger/basic/README.md
- docs/samples/logger/knative-eventing/README.md
- docs/samples/onnx/README.md
- docs/samples/pytorch/README.md
- docs/samples/rollouts/README.md
- docs/samples/s3/README.md
- docs/samples/tensorflow/README.md
- docs/samples/tensorrt/README.md
- docs/samples/transformer/image_transformer/README.md
- docs/samples/xgboost/README.md
Fixes https://github.com/kubeflow/kfserving/issues/760
```release-note
```
> Remove kfserving ingressgateway from doc

- README.md
- docs/samples/s3/README.md
Fixes #841 #827 
```release-note
```
> Doc fixes for cert manager version and s3 secret yaml

- OWNERS
> Renaming ellis-bigelow -> ellistarn

- docs/samples/explanation/alibi/imagenet/README.md
- docs/samples/explanation/alibi/income/README.md
- docs/samples/explanation/alibi/income/income_explanations.ipynb
- install/v0.3.0/kfserving.yaml
* Update READMEs for users of v0.3.0 kfserving.
* Update install for v0.3.0 to use seldon image (same as kubeflow).
> Updates for Alibi use in v0.3.0 release

- test/scripts/run-e2e-tests.sh
fix broken CI for istio installation
```
Error: render error in "istio/charts/gateways/templates/rolebindings.yaml": template: istio/charts/gateways/templates/rolebindings.yaml:4:7: executing "istio/char
ts/gateways/templates/rolebindings.yaml" at <($spec.sds) and (eq $spec.sds.enabled true)>: can't give argument to non-function $spec.sds
error: no objects passed to apply
```
Fixes #
```release-note
```
> Fix broken helm istio install in CI

- python/kfserving/MANIFEST.in
- python/kfserving/setup.py
Fixes #860 
From the document https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files, added MANIFEST.in file.
> Add requirement.txt to pypi source pacakge

- pkg/apis/serving/v1alpha2/inferenceservice_status.go
- pkg/controller/inferenceservice/controller.go
- pkg/controller/inferenceservice/controller_test.go
- pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go
- pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
Adds addition test to showcase event recording when: Ready --> Non-Ready --> Ready
Fixes #881 
> Add additional unit tests to event Recorder

- ROADMAP.md
> Update KFServing roadmap for Q3/Q4

- pkg/controller/inferenceservice/controller_test.go
> Fix Flakey Controller Tests

- README.md
- docs/samples/README.md
- docs/samples/autoscaling/README.md
- docs/samples/bentoml/README.md
- docs/samples/custom-domain/README.md
- docs/samples/custom/hello-world/README.md
- docs/samples/custom/kfserving-custom-model/README.md
- docs/samples/custom/prebuilt-image/README.md
- docs/samples/gcp-iap/README.md
- docs/samples/kafka/README.md
- docs/samples/onnx/README.md
- docs/samples/pytorch/README.md
- docs/samples/rollouts/README.md
- docs/samples/s3/README.md
- docs/samples/sklearn/README.md
- docs/samples/sklearn/perf.yaml
- docs/samples/tensorflow/README.md
- docs/samples/transformer/image_transformer/README.md
- docs/samples/triton/simple_string/README.md
- docs/samples/xgboost/README.md
- hack/quick_install.sh
- Add KFServing feature descriptions along with examples
- Update quick installation with lstio 1.6.2 and KFServing 0.3
Fixes #
```release-note
```
> Update KFServing docs

- config/configmap/inferenceservice.yaml
- config/overlays/test/configmap/inferenceservice.yaml
fix config map format, remove the comma at end of line.
> fix config map format

- README.md
- config/overlays/test/configmap/inferenceservice.yaml
- docs/apis/README.md
- docs/samples/custom/prebuilt-image/README.md
- docs/samples/triton/simple_string/README.md
- pkg/apis/serving/v1alpha2/inferenceservice_types.go
> Update KFServing 0.4 API docs

- docs/samples/logger/basic/README.md
- docs/samples/logger/basic/message-dumper.yaml
- hack/image_patch_dev.sh
- pkg/controller/inferenceservice/resources/knative/service.go
- pkg/logger/collector.go
- pkg/logger/worker.go
- test/e2e/batcher/test_batcher.py
- test/e2e/common/utils.py
- test/e2e/explainer/test_tabular_explainer.py
- test/e2e/logger/test_logger.py
- test/e2e/predictor/test_pytorch.py
- test/e2e/predictor/test_tensorflow.py
- test/e2e/predictor/test_xgboost.py
- test/e2e/transformer/test_transformer.py
The recent batcher change broke the request/response logger since it overwrites the container spec and the logger port change got lost.
Fixes #564 
```release-note
```
>  Fix logger port overwritten by batcher issue and add logger e2e test

- docs/samples/custom/grpc-server/grpc-service.yaml
- docs/samples/custom/hello-world/custom.yaml
- docs/samples/custom/kfserving-custom-model/custom.yaml
- docs/samples/custom/prebuilt-image/custom.yaml
- pkg/apis/serving/v1alpha2/framework_custom.go
Fixes #944
Add container name in custom sample's yaml file
Relax custom container name, remove the default custom container name
Remove the container name comparison.
> Resolve custom sample deploy error.

- docs/PRESENTATIONS.md
> correct Kubeflow spelling

- OWNERS
additionally remove some inactive reviewers
> Add Qingshan Chen from Inspur as a reviewer

- README.md
**What this PR does / why we need it**: Small fix to README.md
Fixes #
```release-note
```
> Fix link to logging documentation in README.md

- README.md
> updated instruction for Curl the `InferenceService` in  README.md #966

- README.md
- docs/samples/istio-dex/README.md
- docs/samples/s3/README.md
- docs/samples/s3/s3_secret.yaml
- hack/quick_install.sh
- test/scripts/sdk-test.sh
Update 0.4 installation instructions
> Update KFS 0.4 installation instruction

- install/v0.4.0/kfserving.yaml
Fixes #975 
1. Published to docker hub until sort out the permission issue for cloud build trigger
```release-note
```
> publish batcher image to docker hub for v0.4.0

- OWNERS
ilan and yuzhui have made various contributions to KFServing and currently working on multi model serving they originally proposed.
> Add ifilonenko & yuzliu as reviewer

- docs/predict-api/v2/required_api.md
This allows a more performant implementation due to the way protobuf
clearing and reuse operates in conjunction with GRPC APIs.
Fixes #
```release-note
```
> Update GRPC protocol to have raw tensor data at top-level of message

- python/kfserving/test/test_storage.py
What this PR does / why we need it:
Special notes for your reviewer: fix minio storage test
Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.
 Release note:
Fix minio storage test
> fix minio storage test

- pkg/apis/serving/v1beta1/trained_model.go
- pkg/apis/serving/v1beta1/trained_model_status.go
Merge TrainedModel api to master branch so 
https://github.com/kubeflow/kfserving/pull/1001 and https://github.com/kubeflow/kfserving/pull/989 can use this pr's ModelSpec struct.
> Trained model api

- docs/KFSERVING_DEBUG_GUIDE.md
Fixes #
```release-note
Add section about common authorization issue related to knative and AWS ECR
```
> Add common case for knative authorization issue

- docs/PRESENTATIONS.md
Add ICML Presentation
```release-note
Add ICML Presentation
```
> Add ICML Presentation

- python/alibiexplainer/setup.py
Shap recently updated their library with a breaking change release which has not been picked up by Alibi.
Until we use an updated Alibi we will need to fix shap to 0.35
Fixes #1052
```release-note
```
> Fix shap version to 0.35

- README.md
- hack/quick_install.sh
Try to ensure a working version of Kubernetes. 
Fixes #1054 
Probably #1003 
```release-note
NONE
```
> document working k8s version

- pkg/apis/serving/v1alpha2/inferenceservice_validation.go
- pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go
- pkg/apis/serving/v1beta1/component.go
- pkg/apis/serving/v1beta1/inference_service_validation.go
- pkg/apis/serving/v1beta1/inference_service_validation_test.go
. Check if ISVC name starts with alphabetical character.
Fixes #1059
Fixes #
```release-note
```
> Validation check for InferenceService Name

- test/benchmark/README.md
Minor typo which might lead to confusion. The `parallelism` shall be one level down to `predictor` in example yaml file.
None. Just typo in documentation.
None
```release-note
NONE
```
> Fix typo in benchmark doc

- docs/samples/onnx/onnx.yaml
- docs/samples/triton/bert/bert.yaml
Fixes https://github.com/kubeflow/kfserving/issues/1108
```release-note
```
> Use kfserving-examples gs bucket

- config/default/params.env
- config/overlays/kubeflow/params.env
The value of ingressGateway in inferenceservice-config ConfigMap needs to be separated by a comma.
Fixes #
```release-note
```
> add a comma at the end of ingressGateway name

- config/default/kustomization.yaml
- config/overlays/kubeflow/kustomization.yaml
- hack/generate-install.sh
We use "kustomize build" instead of "kubectl kustomize" to avoid many changes.
To use existing one, some keyword should be changed for compatibility.
Fixes #
```release-note
```
> use "kustomize build" instead of "kubectl kustomize"

- OWNERS
> Add David Goodwin as approver

- cmd/manager/main.go
- config/rbac/role.yaml
- config/webhook/service.yaml
- pkg/controller/inferenceservice/controller.go
This PR cherrypicks two OpenShift fix commits (#1122 and #1134) in preparation for minor release (0.4.1).
```release-note
```
> Cherry-pick of OpenShift fixes (#1122 and #1134) to release-0.4

- docs/DEVELOPER_GUIDE.md
This part of the dev docs could use updating and one of the links 404s.
- Update the developer guides knative links and wording to be accurate
- Improve wording around metrics and tracing and provide link
Updates Knative installation docs, improve logging metrics section.
> Update developer guide knative links

- README.md
> bump up minimal Kube and Istio requirements

- install/v0.4.1/kfserving.yaml
regenerating release yaml changes only these - hope that's all there to it?
> update v0.4.1 release yaml

- install/v0.4.1/kfserving.yaml
for k8s 1.18 support needed for openshift v4.5
> update 0.4.1 yaml

- cmd/manager/main.go
Fixes https://github.com/kubeflow/kfserving/issues/1171
```release-note
```
> Allow unknown fields when unmarshalling istio resources

- README.md
update knative to 0.14.3, and make it clear the min Kubernetes is 1.15
> update knative version

- docs/samples/custom/torchserve/README.md
- docs/samples/custom/torchserve/docs/canary.md
- fix readme
- fix canary readme
Fixes #
```release-note
```
> Fix: Torchserve readme docs

- README.md
- docs/OPENSHIFT_GUIDE.md
- docs/samples/README.md
Update and point to main install instructions for KFServing on OpenShift, and AIX360 integration sample in sample directory
> OpenShift Install Instrcutions + AIX360 in main samples

- README.md
This PR fixes the missing API version in the samples path on README.md.
> Fix: Missing API version in the samples path

- OWNERS
@adriangonz has been contributing MLServer integration to KFServing, let's add him as reviewer.
Fixes #
```release-note
```
> Add adriangonz as reviewer

- Dockerfile
- docs/samples/kafka/README.md
- docs/samples/kafka/image_transformer/image_transformer.py
- docs/samples/kafka/kafka-source.yaml
- docs/samples/kafka/minio.yaml
- docs/samples/kafka/mnist_kafka.yaml
- docs/samples/kafka/s3_secret.yaml
- docs/samples/kafka/transformer.Dockerfile
- pkg/apis/serving/v1beta1/component.go
- pkg/apis/serving/v1beta1/explainer_aix360.go
- pkg/apis/serving/v1beta1/explainer_alibi.go
- pkg/apis/serving/v1beta1/explainer_custom.go
- pkg/apis/serving/v1beta1/predictor_custom.go
- pkg/apis/serving/v1beta1/predictor_onnxruntime.go
- pkg/apis/serving/v1beta1/predictor_pmml.go
- pkg/apis/serving/v1beta1/predictor_sklearn.go
- pkg/apis/serving/v1beta1/predictor_tfserving.go
- pkg/apis/serving/v1beta1/predictor_torchserve.go
- pkg/apis/serving/v1beta1/predictor_triton.go
- pkg/apis/serving/v1beta1/predictor_xgboost.go
- pkg/apis/serving/v1beta1/transformer_custom.go
- pkg/constants/constants.go
- pkg/controller/v1alpha2/inferenceservice/controller_test.go
- pkg/controller/v1alpha2/inferenceservice/resources/istio/virtualservice_test.go
- pkg/controller/v1beta1/inferenceservice/controller_test.go
- pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Fixes #
1. Update eventing addressable url based on v1 or v2 inference protocol, note that this should only work with single model service for multi model service it is not applicable as KFS do not know which model to invoke.
```release-note
```
> Update and fix kafka example for v1beta1

- docs/samples/v1beta1/torchserve/imgconv/img2bytearray.py
Fix image converter that converts iamge to bytesarray json structure for torchserve request
Fixes #
```release-note
fix image converter for image to torchserve request conversion
```
> Fix: image converter for torchserve

- config/configmap/inferenceservice.yaml
- config/overlays/test/configmap/inferenceservice.yaml
- hack/quick_install.sh
- Update inferenceservice config map with torchserve 0.3 version
- Update qucik_install.sh with v0.5.0-rc1 version
Fixes #
```release-note
```
> Fix: Update inference config map with torchserve 0.3

- docs/samples/v1beta1/torchserve/README.md
- docs/samples/v1beta1/torchserve/docs/metrics.md
- docs/samples/v1beta1/torchserve/metrics.yaml
- hack/quick_install.sh
> Fix: Use istio's grafana and prometheus addons for torchserve metrics

- config/configmap/inferenceservice.yaml
> Add jagadeeshi2i to reviewer

- README.md
Correct the location of sklearn/perf.yaml file in README.md
Fixes #
```release-note
```
> Fix readme to correct sklearn perf.yaml location

- docs/DEVELOPER_GUIDE.md
latest yq version 4.* has removed '-d' command so won't work with the scripts. Update developer guide with compatible yq version 3.* 
Fixes #
```release-note
```
> Update developer guide with compatible yq version 3.*

- config/configmap/inferenceservice.yaml
- config/overlays/test/configmap/inferenceservice.yaml
- docs/samples/v1beta1/sklearn/README.md
- docs/samples/v1beta1/sklearn/requirements.txt
- docs/samples/v1beta1/xgboost/README.md
- docs/samples/v1beta1/xgboost/requirements.txt
- pkg/apis/serving/v1beta1/predictor_sklearn.go
- pkg/apis/serving/v1beta1/predictor_sklearn_test.go
- pkg/apis/serving/v1beta1/predictor_xgboost.go
- pkg/apis/serving/v1beta1/predictor_xgboost_test.go
- pkg/constants/mlserver.go
This PR adds support for MMS for Scikit-Learn and XGBoost when using the V2 protocol. 
Fixes #1240
```release-note
Add Multi-Model Serving support for Scikit-Learn and XGBoost with the V2 protocol.
```
> Add MMS support for Scikit-Learn and XGBoost V2

- docs/OPENSHIFT_GUIDE.md
* Fixed a few broken links
* Added a command to ensure users install a specific release
> Update OpenShift documentation

- docs/predict-api/v2/README.md
- docs/predict-api/v2/grpc_predict_v2.proto
This PR adds a grpc inferencing proto file which follows the spec https://github.com/kubeflow/kfserving/blob/master/docs/predict-api/v2/required_api.md
Then this PR updates the doc to point to the local spec rather than pointing to the triton-inference-server version.
This is needed because some organizations my not be keen on or able to pull in the proto file with the NVIDIA copyright.
None
```release-note
NONE
```
> Reference local copy of predict v2 grpc proto file

- ADOPTERS.md
Adds Halodoc ID to adpoters.md
Fixes #
**Special notes for your reviewer**: None
NONE
> Adds Adopters.MD, adding Halodoc ID to the list

- config/overlays/test/configmap/inferenceservice.yaml
- config/overlays/test/manager_image_patch.yaml
- test/e2e/transformer/test_transformer.py
- test/scripts/run-e2e-tests.sh
- test/workflows/components/workflows.libsonnet
Migrate kfserving to new test-infra
Fixes #1326 
```release-note
None
```
> Migrate kfserving to new test-infra

- pkg/agent/downloader.go
- pkg/agent/storage/utils.go
- pkg/agent/syncer.go
- pkg/agent/watcher.go
- pkg/agent/watcher_test.go
Fixes #1317 
1. Generate sha for the model spec instead of individual fields
2. Fix FileExist util function as there could be other PathError if not `FileNotExist`
```release-note
```
> Fix FileExist utility and generate sha for modelspec

- docs/samples/v1alpha2/onnx/README.md
- docs/samples/v1alpha2/pmml/README.md
- docs/samples/v1alpha2/pytorch/README.md
- docs/samples/v1alpha2/rollouts/README.md
- docs/samples/v1alpha2/sklearn/README.md
- docs/samples/v1alpha2/tensorflow/README.md
- docs/samples/v1alpha2/xgboost/README.md
Found it when I try to run some examples. Just a quick fix of the link.
> Fix broken link

- OWNERS
Has been reviewing and maintaining KFServing-Kubeflow manifests
> Add Paul as a reviewer for KFServing

- docs/OPENSHIFT_GUIDE.md
This PR provides documentation for installing and using KFServing with OpenShift Service Mesh.
> Update KFServing on OpenShift documentation

- README.md
Document an easy way to curl inference service with magic dns
Fixes #
```release-note
```
> Instruction for calling inference service with magic DNS

- python/kfserving/kfserving/handlers/http.py
- python/kfserving/kfserving/kfmodel.py
- python/kfserving/test/test_server.py
Bug Fix for Cloud Event data access
Fixes #
```release-note
```
> Bug Fix for CloudEvent data access

- docs/MULTIMODELSERVING_GUIDE.md
- docs/samples/v1beta1/sklearn/v1/multimodel/README.md
- docs/samples/v1beta1/triton/multimodel/README.md
**What this PR does / why we need it**: Fixed broken link and emphasize need to change `multiModelServing` flag
Fixes #
```release-note
None
```
> Update Multi-Model Serving Doc

- pkg/controller/v1alpha2/inferenceservice/controller_test.go
**What this PR does / why we need it**: We currently do not check if default is non-nil and try to dereference the pointer. This could potentially lead to invalid memory address or nil pointer dereference errors.
Fixes #
```release-note
None
```
> Check if isvc.Status.Default is not nil before trying to access pointer

- docs/samples/v1beta1/transformer/torchserve_image_transformer/README.md
- docs/samples/v1beta1/transformer/torchserve_image_transformer/image_transformer/__main__.py
- docs/samples/v1beta1/transformer/torchserve_image_transformer/setup.py
- docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer.Dockerfile
- docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer.yaml
Update torchserve transformer doc to clarify how to implement the transformer and how `STORAGE_URI` can be used.
Fixes #
```release-note
```
> Update Torchserve transformer doc

- python/kfserving/setup.py
Closes: https://github.com/kubeflow/kfserving/issues/1430
> Fix PyPI link

- README.md
Document requirement to use `PodTemplate` fields.
Fixes #1425 
```release-note
```
> Add requirement to use PodTemplate fields

- README.md
add pointers to KFS monitoring setup using Prometheus, and add links for iter8 integration
> update monitoring pointers

- OWNERS
Add me as a reviewer
/cc @yuzisun
> Add Theo in reviewers

- pkg/apis/serving/v1alpha1/trainedmodel_webhook.go
- pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
**What this PR does / why we need it**: Update tm name regex to match https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/kfserver.py#L77 for consistency
Fixes #
```release-note
None
```
> Update tm name regex

- README.md
> Update README.md version to 0.5.1

- cmd/agent/main.go
- docs/samples/batcher/basic/batcher_v1beta1.yaml
- go.mod
- pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
- pkg/batcher/handler.go
- pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
- pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
- pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
- pkg/webhook/admission/pod/agent_injector.go
- pkg/webhook/admission/pod/agent_injector_test.go
> Cherry pick #1509 #1484

- agent.Dockerfile
- pkg/webhook/admission/pod/agent_injector.go
- pkg/webhook/admission/pod/agent_injector_test.go
**What this PR does / why we need it**: Agent built with ko has a different entry point as built with docker. Default to use `/ko-app/agent`
Fixes #1435
```release-note
```
> Default agent path /ko-app/agent

- docs/samples/storage/s3/README.md
- docs/samples/storage/s3/s3_secret.yaml
- docs/samples/storage/s3/tensorflow_s3.yaml
Fixes #1519 
```release-note
```
> Update S3 example doc

- pkg/controller/v1beta1/inferenceservice/controller_test.go
- pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
…updated (#1525)
Fixes #
```release-note
```
> Cherrypick #1525 to release-0.5

- .github/workflows/web-app-docker-publish.yml
Fixes #1504 
I've made the following assumptions in this PR:
1. The app is named `models-web-app`, since the `InferenceService` objects are model servers
2. It's using the `kfserving/models-web-app` image name
3. I've used the yaml from [alibiexplainer-docker-publish.yml](https://github.com/kubeflow/kfserving/blob/master/.github/workflows/alibiexplainer-docker-publish.yml) and slightly modified for this action
I don't have any hard preference for the name so if you'd like to use a different name feel then please let me know and I'll change it accordingly. …
> Add a GH action for the ui

- python/xgbserver/xgbserver/model.py
See #1513 
Fixes #
```release-note
```
> Cherry Pick #1513

- pkg/agent/downloader.go
- pkg/agent/storage/https.go
- pkg/agent/storage/provider.go
- pkg/agent/storage/utils.go
- pkg/agent/watcher_test.go
- pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go
**What this PR does / why we need it**: Introduces HTTPS protocol for multi-model serving. Now mms will be able to download files from s3, gcs, and https.
Fixes #
```release-note
None
```
> Introducing HTTPS protocol for MMS

- cmd/agent/main.go
- pkg/agent/downloader.go
- pkg/agent/puller.go
- pkg/agent/watcher_test.go
This PR aims to fix: https://github.com/kubeflow/kfserving/issues/1531
Fixes #1531
```release-note
```
> fix(bug): Added mutext for downloader providers. Fixes #1531

- docs/samples/v1beta1/spark/sparkml.py
> Fix python lint in the spark pmml example

- web-app/README.md
Add a `Connect to the app` and `Configuration` sections to provide clear instructions to the users on how to connect and configure the app.
cc @yuzisun @pvaneck 
/cc @elikatsis @tasos-ale
> Update the README of the web app

- docs/apis/v1beta1/README.md
- hack/violation_exceptions.list
- pkg/apis/serving/v1beta1/openapi_generated.go
- pkg/apis/serving/v1beta1/swagger.json
* update apidocs
* update openapi spec to have up-to-date descriptions in go.dev
* update swagger
> Docs update

- python/sklearnserver/README.md
> fix(docs): update broken link in sklearn predictor README

- pkg/apis/serving/v1beta1/openapi_generated.go
- pkg/apis/serving/v1beta1/predictor_xgboost.go
- pkg/apis/serving/v1beta1/swagger.json
> fix(docstring): fix docstring for XGB predictor. 

- docs/samples/kafka/README.md
- docs/samples/kafka/setup.py
…inio and Kafka
**Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):**
Fixes #1439
```release-note
NONE
```
> docs: fixes gsutil command in the End to end kafka inference example

- docs/samples/v1beta1/torchserve/README.md
- docs/samples/v1beta1/torchserve/bert/config.properties
- docs/samples/v1beta1/torchserve/config.properties
Fix torchserve v1beta1 examples for enabling KFServing inference protocol
Fixes #1542 
```release-note
```
> Fix torchserve v1beta1 examples for enabling KFServing inference protocol

- docs/samples/logger/knative-eventing/README.md
The outdated image does not work, see https://github.com/knative/docs/issues/2145 for more context.
Fixes #
```release-note
```
> Update path in README to be consistent with code

- config/configmap/inferenceservice.yaml
- config/overlays/test/configmap/inferenceservice.yaml
- pkg/apis/serving/v1beta1/predictor_torchserve_test.go
- pkg/controller/v1beta1/inferenceservice/utils/utils_test.go
This PR adds torchserve version 0.4.0
Fixes #1560
```
Upgraded torchserve version to 0.4.0
```
> Feature: Upgrade torchserve-kfs version

- Makefile
- hack/misc_patch_dev.sh
- hack/storageInitializer_patch_dev.sh
Fixes #1610
```release-note
```
> Fixes storage initializer image patch script

- python/kfserving/kfserving/storage.py
- python/kfserving/test/test_s3_storage.py
Checks whether env var awsAnonymousCredential true
to use S3 resource config anonymous
addresses issue #1581
Signed-off-by: Malini Bhandaru <mbhandaru@vmware.com>
Fixes #1581
```release-note
```
> supports anonymous S3 connect

- pkg/agent/storage/https.go
- python/kfserving/kfserving/storage.py
- python/kfserving/test/test_storage.py
When `storageUri` is a URI with a suffix of `.tar.gz` or `.tgz`, the current Kfserving requires `response.header.Content-Type=application/x-tar`. However, [IANA didn't define a MIME type for .tar.gz files](https://www.iana.org/assignments/media-types/media-types.xhtml), and many sites are using different `Content-Type`. Therefore, I opened the pull request to allow some other `Content-Type` for `.tar.gz` files.
Ref
- https://www.iana.org/assignments/media-types/media-types.xhtml
- https://en.wikipedia.org/wiki/List_of_archive_formats
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
- https://github.com/python/cpython/blob/3.9/Lib/mimetypes.py
- https://stackoverflow.com/questions/28396703/mime-type-for-tgz
- …
> relax .tar.gz files Content-Type check

- hack/quick_install.sh
The issues comes from cert-manager. Even though the pods are ready the service is still not available due to it may take a minute or so for the TLS assets required for the webhook to function to be provisioned, [docs](https://cert-manager.io/docs/installation/kubernetes/#verifying-the-installation)
The issue can be recreated:
Deployment  cert manager:
```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.4.0/cert-manager.crds.yaml
```
check for all pods running
```
kubectl get pods --namespace cert-manager
```
create test data
```
cat <<EOF > test-resources.yaml
apiVersion: v1
kind: Namespace
metadata:
name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
name: test-selfsigned
namespace: cert-manager-test
spec:
selfSigned: {}
--- …
```
> feat(bug): retry kfserving installation. Fixes #1613

- docs/DEVELOPER_GUIDE.md
**What this PR does / why we need it**: Above
```release-note
None
```
> Correct Tensorflow sample's URL in the Dev Guide

- docs/DEVELOPER_GUIDE.md
Following up #1686
**What this PR does / why we need it**: See above
Fixes #
```release-note
None
```
> Correct link to the tensorflow sample

- README.md
- docs/samples/v1alpha2/transformer/image_transformer/setup.py
- hack/quick_install.sh
- python/aiffairness/setup.py
- python/aixexplainer/setup.py
- python/alibiexplainer/setup.py
- python/artexplainer/setup.py
- python/lgbserver/setup.py
- python/paddleserver/setup.py
- python/pmmlserver/setup.py
- python/pytorchserver/setup.py
- python/sklearnserver/setup.py
- python/xgbserver/setup.py
> Update 0.6 installation doc

- docs/samples/storage/azure/README.md
- python/kfserving/kfserving/storage.py
- python/kfserving/requirements.txt
- python/kfserving/test/test_azure_storage.py
Fixes # https://github.com/kubeflow/kfserving/issues/923
```
1. Upgraded Azure Blob to 12.1.0 as part of the storage initializer in KFServing. 
```
> Update Azure Blob to 12.1.0

- docs/samples/v1beta1/rollout/README.md
- pkg/apis/serving/v1beta1/inference_service_status.go
- pkg/constants/constants.go
- pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
Fixes #1672 
1. this PR also fixed an issue when a revision was fully rolled out but then rolled back to previous version, kfserving incorrectly split the traffic to a potentially bad revision.
```release-note
```
> Enable tag based routing 

- docs/samples/multimodelserving/benchmark/BENCHMARK.md
Signed-off-by: ted chang <htchang@us.ibm.com>
Fix broken url to the MULTIMODELSERVING_GUILD.md
```release-note
NONE
```
> Update broken url to the MULTIMODELSERVING_GUIDE.md
