kubeflow/kfserving

pkg/apis/serving/v1alpha1/kfservice_validation.go, pkg/apis/serving/v1alpha1/kfservice_validation_test.go, pkg/reconciler/ksvc/reconciler.go
A recent commit broke these tests. They're working now. +1 to automating testing.
➜  kfserving git:(validate) make all
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/Users/ellisbigelow/go/src/github.com/kubeflow/kfserving/config/crds'
RBAC manifests generated under '/Users/ellisbigelow/go/src/github.com/kubeflow/kfserving/config/rbac'
go test ./pkg/... ./cmd/... -coverprofile cover.out
?   	github.com/kubeflow/kfserving/pkg/apis	[no test files]
?   	github.com/kubeflow/kfserving/pkg/apis/serving	[no test files]
ok  	github.com/kubeflow/kfserving/pkg/apis/serving/v1alpha1	8.309s	coverage: 42.5% of statements
? …
=> Fixes broken validation tests.

pkg/apis/serving/v1alpha1/kfservice_defaults.go
- version 1.12 does not exist and upgrade to 1.13.0 which starts to support REST call.
- these versions later should be moved to configmap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/66)
=> Fix default tensorflow image

docs/DEVELOPER_GUIDE.md, test/README.md
- Add perquisite installation guide
- Add test/deploy iteration guide
- Note that `make deploy-test` is introduced in https://github.com/kubeflow/kfserving/pull/65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/67)
=> Add Developer guide for KFServing

pkg/controller/kfservice/kfservice_controller.go, pkg/reconciler/ksvc/reconciler.go, pkg/reconciler/ksvc/reconciler_test.go
for knative serving,  it reconciles `Labels` of configuration and route, not just spec. refer to [here](https://github.com/knative/serving/blob/master/pkg/reconciler/service/service.go#L414)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/64)
=> Reconcile labels and annotations for configuration/route

pkg/controller/kfservice/kfservice_controller_test.go, pkg/reconciler/ksvc/reconciler_test.go, pkg/reconciler/ksvc/resources/knative_configuration.go, pkg/reconciler/ksvc/resources/knative_configuration_test.go
`RevisionTemplate` field is dropped now, `Template` replaced it instead in Knative serving
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/78)
=> Remove DEPRECATED RevisionTemplate

pkg/controller/kfservice/kfservice_controller_test.go, pkg/reconciler/ksvc/reconciler_test.go, pkg/reconciler/ksvc/resources/knative_configuration.go, pkg/reconciler/ksvc/resources/knative_configuration_test.go
This reverts commit b6ec6e65440e19c99637f923ac099ce716a0bceb.
Looks like this change doesn't work. Am I running an outdated knative install?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/81)
=> Revert "Remove DEPRECATED RevisionTemplate (#78)"

docs/samples/sklearn/README.md, python/kfserving/README.md, python/kfserving/kfserving/storage.py, python/kfserving/kfserving/test_storage.py
The current `kfserving.storage` implementation only takes absolute local paths. It should also apply to any relative/absolute local path that exists on the local system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/92)
=> Made python kfserving.storage return uri if local path exists

OWNERS
Hey Clive, Dan, and Abhishek, 
Animesh has been helping coordinate IBM resources (Tommy Li, Guang Ya Liu, and Hougang Liu) to help with KFServing. He's been improving our docs to be more cohesive and has contributed sklearn compatibility. He's also made significant contributions to the discussion in KFServing weeklies.
In the interest of maintaining a diverse set of perspectives and a strong foundation of stakeholders from different organizations, I propose adding him as an approver on this project.
I'd like to hold until there is unanimous support from you all. My only reservation is that I'd like to see Animesh (or a representative IBMer) attending our weeklies. It's important that at minimum, all approvers remain on the same page regarding project technical direction and product …
=> Adds Animesh as an Approver

pkg/apis/serving/v1alpha1/v1alpha1_suite_test.go, pkg/controller/kfservice/kfservice_controller_suite_test.go, pkg/reconciler/ksvc/ksvc_suite_test.go, prow_config.yaml
After `config/crds` dir changed, tests which depend on files of it need be updated, too. Also, include `config` dir into prow config to make changes of `config` trigger test, too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/96)
=> Fix test error caused by crds dir changed

python/sklearnserver/sklearnserver/test_model.py
Since #92, we now can load files using relative path. This fix makes the python scikit-learn test cases actually work with the correct `model_dir` relative path.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/98)
=> Fix python sklearn test cases with the correct model_dir

config/default/manager/service.yaml
This fixes an issue with k8s 1.12 admission webhooks not playing nicely with certificates.
Knative turns it off:
```
kubectl get deployments webhook -n knative-serving -o=jsonpath='{.spec.template.metadata.annotations}'
map[sidecar.istio.io/inject:false]%
```
Istio turns it off:
```
kubectl get namespace istio-system -o jsonpath="{.metadata.labels.istio-injection}"
disabled%
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/103)
=> Disables istio-injection in the namespace

config/default/kustomization.yaml, config/default/manager/manager.yaml, config/default/manager/service.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_image_patch.yaml, config/default/manager_prometheus_metrics_patch.yaml, config/default/rbac/auth_proxy_role.yaml, config/default/rbac/auth_proxy_role_binding.yaml, config/default/rbac/auth_proxy_service.yaml, image_patch_dev.sh
Kustomize prefix is typically used for namespacing different deployments in the same cluster (i.e., deploying both dev and prod to the same cluster).
I see namespacing based off of our kfserving name as an anti-pattern, as none of these resources should be fundamentally renamed by any consumer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/104)
=> Removes kfserving prefix from Kustomize and explicitly applies it to all resources

hack/boilerplate.go.txt, hack/boilerplate.python.txt, hack/boilerplate.sh, pkg/constants/constants.go, pkg/reconciler/ksvc/resources/knative_configuration.go, pkg/reconciler/ksvc/resources/knative_route.go, pkg/reconciler/ksvc/resources/knative_route_test.go, pkg/webhook/admission/kfservice/kfservice_defaulter.go, pkg/webhook/admission/kfservice/kfservice_validator.go, pkg/webhook/webhook.go, python/kfserving/kfserving/__init__.py, python/kfserving/kfserving/model.py, python/kfserving/kfserving/protocols/request_handler.py, python/kfserving/kfserving/protocols/seldon_http.py, python/kfserving/kfserving/protocols/tensorflow_http.py, python/kfserving/kfserving/server.py, python/kfserving/kfserving/storage.py, python/kfserving/kfserving/test_server.py, python/kfserving/kfserving/test_storage.py, python/kfserving/setup.py, python/sklearnserver/setup.py, python/sklearnserver/sklearnserver/__init__.py, python/sklearnserver/sklearnserver/__main__.py, python/sklearnserver/sklearnserver/model.py, python/sklearnserver/sklearnserver/test_model.py, python/xgbserver/setup.py, python/xgbserver/xgbserver/__init__.py, python/xgbserver/xgbserver/__main__.py, python/xgbserver/xgbserver/model.py, python/xgbserver/xgbserver/test_model.py
Add copyright generation script so that developer does not need to manually add for each file. The script checks each of go files under `pkg` and python files under `python` directory for  the existence of copyright header, if it does not present the script then concatenate the copyright file and source code file.   
```
cd hack
./boilerplate.sh
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/105)
=> Add copyright script and generate for go/python files which are missing headers

config/default/manager_image_patch.yaml, release/README.md, release/cloud-build-configs/kfserving-controller.cloud-build.yaml
This PR enables images built from HEAD. This will be the foundation of our image versioning system. The images will be provided in gcr.io and paid for by Google until further notice.
I was considering going the PROW route, but I'm really not a fan of the kubeflow infrastructure for this. This enables a simple, straightforward, cloudbuilder experience to build images for head.
Of course, our release process will mature over time, but I imagine we being cutting release branches which tag images after successful e2e testing.
NONE
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/99 …
=> Adds release for automated GitOps triggered image builds for KFServing

Gopkg.lock, pkg/reconciler/ksvc/resources/knative_configuration.go, pkg/reconciler/ksvc/resources/knative_configuration_test.go
What this PR does / why we need it:
This PR sets the ServiceAccountName on the Kantive Configuration PodSpec.
Enables pulling images from private registries for KfService etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/115)
=> Set ServiceAccount on Knative Configuration

docs/DEVELOPER_GUIDE.md
Seems the sample file `docs/samples/tensorflow.yaml` in developer guide has been removed by PR #118 , the PR is to correct file path to point the `tensorflow` folder sample so that the developer guide is performable. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/124)
=> update developer guide to correct file path

python/kfserving/README.md, python/kfserving/kfserving/storage.py, python/kfserving/kfserving/test_storage.py, python/kfserving/setup.py, python/sklearn.Dockerfile, python/xgb.Dockerfile
This PR implements the python model download methods for S3 and GCS. Since KFServing can provide S3 and GCS credentials as environment variables, we will be using those environment variables for user authentication.
I also added the gsutil to the docker images since we need it for accessing public GCS data artifacts.
Fixes #87
1. It would be nice if we can upload the current sklearn and xgboost sample models to the `gs://kfserving-samples` bucket, so we can update the example to use gcs and don't have to include the sample models in the docker image. …
=> Added the python model download methods for S3 and GCS.

pkg/apis/serving/v1alpha1/kfservice_framework.go, pkg/apis/serving/v1alpha1/v1alpha1_suite_test.go, pkg/controller/kfservice/kfservice_controller_suite_test.go
Use klog for kfserving. As most of the Kubernetes projects are using klog, it is better for kfserving migrate to this as well.
fixes #89 
The PR is to use klog (replacing log) for kfserving.
The PR does not update `sigs.k8s.io/controller-runtime/pkg/runtime/log` that's used in the kfserving,  since the issue for klog at https://github.com/kubernetes/klog/issues/22, the klog cannot handle the case of some sort with a predefined set of variables which are used as suffix for each log line.  Leave the part for now as katib repo in https://github.com/kubeflow/katib/issues/506, may be updated later. Thanks.
```release-note
Used klog for kfserving.
```
---
This change …
=> Use klog for kfserving

docs/samples/sklearn/sklearn.yaml, docs/samples/xgboost/xgboost.yaml, python/sklearn.Dockerfile, python/xgb.Dockerfile
Corrects the storage location for sklearn and xgboost, and removes copying of models in docker containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/131)
=> Add correct URLs for sklearn and xgboost

pkg/constants/constants.go, pkg/webhook/webhook.go
Before this PR, kfserving webhookconfigurations names are used by default value `mutating-webhook-configuration` and `validating-webhook-configuration` as below
```
NAME                                 CREATED AT
istio-sidecar-injector               2019-05-14T12:11:23Z
mutating-webhook-configuration       2019-06-10T01:37:34Z
webhook.serving.knative.dev          2019-05-14T23:55:01Z
NAME                                   CREATED AT
istio-galley                           2019-05-14T12:12:07Z
validating-webhook-configuration       2019-05-31T00:49:14Z
```
After this PR, it looks like below
```
NAME                                 CREATED AT
istio-sidecar-injector               2019-05-14T12:11:23Z
kfservice.serving.kubeflow.org …
```
=> Specify kfserving-related WebhookConfigName

README.md, python/sklearnserver/README.md
During viewing the docs, found one bad link in overall README file and a typo in sklearnserver/README.md. The PR is to fix the simple problems. Thanks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/154)
=> fix bad link and typo in docs

pkg/controller/kfservice/resources/credentials/gcs/gcs_secret.go, pkg/controller/kfservice/resources/credentials/gcs/gcs_secret_test.go, pkg/controller/kfservice/resources/credentials/service_account_credentials.go, pkg/controller/kfservice/resources/credentials/service_account_credentials_test.go
Fix the gcs secret volume mount path, the path should not be included on the mount path since key-value pair in the data field of the secret will be projected into the volume as a file whose name is the key and content is the value.
Fixes #
Create the following secret, the key of the secret is `application_default_credentials.json` and value is the content of the file. 
```
kubectl create secret generic dsun-gcs --from-file=/Users/dsun20/.config/gcloud/application_default_credentials.json
```
when you create volume mount we only need to specify the mount …
=> Fix gcs secret volume mount path

python/kfserving/kfserving/server.py
Tensorflow protocol was not default in latest python changes. This fixes this.
Current samples won't work until this is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/176)
=> make tensorflow protocol default

hack/image_patch_dev.sh
fix one problem in new kustomize, see more #223 
Fixes #223 
Before the PR with kustomize 3.0.0:
```
(python36) [root@jinchi1 kfserving]# kustomize version
Version: {KustomizeVersion:3.0.0 GitCommit:e0bac6ad192f33d993f11206e24f6cda1d04c4ec BuildDate:2019-07-03T18:21:24Z GoOs:linux GoArch:amd64}
(python36) [root@jinchi1 kfserving]#
(python36) [root@jinchi1 kfserving]# kustomize build config/overlays/development
Error: no matches for OriginalId apps_v1_StatefulSet|~X|kfserving-controller-manager; no matches for CurrentId apps_v1_StatefulSet|~X|kfserving-controller-manager; failed to find unique target for patch apps_v1_StatefulSet|kfserving-controller-manager
```
With the PR with …
=> fix one problem in new kustomize 3.0.0

python/kfserving/kfserving/storage.py
Download local currently skips copy which is great in most cases... however this doesnt work for the model initializer. Updating to create symlinks if out_dir is set should fix this.
@jinchihe do you feel like helping me verify this fixes pvc:// support with model initializer?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/216)
=> download_local should symlink if outdir is set

Makefile
`make install` fails as needs kustomize.
`make deploy` already installs the CRD and is referenced in developer docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/232)
=> Remove install from Makefile

docs/samples/tensorrt/README.md
Now that we have knative 0.7 the workaround is no longer needed!
Fixes #165
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/254)
=> Remove NVCR.io workaround

sdk/README.md, sdk/docs/KFServingClient.md, sdk/kfserving/__init__.py, sdk/kfserving/api/__init__.py, sdk/kfserving/api/kf_serving_client.py, sdk/kfserving/constants/constants.py, sdk/kfserving/utils/utils.py, sdk/sample/kfserving_sdk_sample.ipynb, sdk/test/test_kfservice_client.py, test/scripts/sdk-test.sh, test/workflows/components/workflows.libsonnet
1. Add basic apis for kfserving SDK: deploy, get, patch, delete.
2. Add sample for the kfserving SDK apis.
3. Updated `hack/update-openapigen.sh` to address @yuzisun comments for that the knative file adding two lines `+k8s:openapi-gen=true`
4. Added sdk unit test into CI/CD testing, and added 4 cases for kfserving apis since the test cluster should no KFServing CRD, for now we just add unit test case, but we need to add real test case for SDK later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/245)
=> add basic sdk api and sample notebook

pkg/apis/serving/v1alpha1/kfservice_status.go, pkg/controller/kfservice/kfservice_controller.go, pkg/controller/kfservice/kfservice_controller_test.go, pkg/controller/kfservice/reconcilers/knative/configuration_reconciler.go
Status has to be initialized before reconcile.  Else Status will have stale values. This is a safe option as all required status fields are recomputed during reconcile.  
How to reproduce
`kubectl apply -f  docs/samples/tensorflow/tensorflow.yaml `
`kubectl apply -f  docs/samples/tensorflow/tensorflow-canary.yaml `<-Canary status is updated
`kubectl apply -f  docs/samples/tensorflow/tensorflow.yaml ` <- Canary status still remains though new spec doesn't have canary block. 
Fixes #
1. Please confirm that if this PR changes any image versions, then that's the …
=> Fix reconcile logic for canary spec 

sdk/docs/KFServingClient.md, sdk/kfserving/api/kf_serving_client.py
Alllow user can set the `kube_config` to loads authentication and cluster information from `kube_config` file.
Fixes item 1 in the #263 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/279)
=> allow user can set kube_config in sdk client

pkg/apis/serving/v1alpha1/kfservice_status.go, pkg/controller/kfservice/kfservice_controller_test.go
ClearCondition function is implemented in ConditionSet which clears a non-terminal condition. CanaryPredictorReady is cleared when canary spec is empty.
Fixes: #276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/285)
=> Adding ClearCondition fix

pkg/apis/serving/v1alpha2/framework.go, pkg/apis/serving/v1alpha2/kfservice_defaults_test.go
Fix the bug that resources limits are not defaulted when it is not specified on KFService spec and knative's default limit is smaller than KFService's default requests.
Fixes https://github.com/kubeflow/kfserving/issues/291
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/293)
=> Set default resource limits for KFService

test/scripts/build-python-image.sh
I always hit some presubmit timeout problem for while pytorchserver building as below.
```
Removing intermediate container 6cb3f3f8be8b
---> 1a3a8eb6797a
Step 11/11 : ENTRYPOINT ["python", "-m", "pytorchserver"]
Your build timed out. Use the [--timeout=DURATION] flag to change the timeout threshold.
ERROR: (gcloud.builds.submit) build f9314385-826e-4dcf-913f-24abf06f9fce completed with status "TIMEOUT"
---> Running in 4d7ec527356e
```
Checked,  If timeout is not set, a default timeout of 10 minutes will apply to the build. Seems the build may be cannot finished in the 10 minutes, we should extend the time.
Fixes #303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> fix pytouch build timeout issue in presubmit

config/default/configmap/kfservice.yaml
#327 changed the image name for the initializer. However the new one is not available in GCR. Point to a custom one for now. Have opened an issue to revert this..
Fixed commits from #330
/assign @yuzisun
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/333)
=> Temporarily point to custom location for storage-initializer

pkg/apis/serving/v1alpha2/framework_scikit.go, pkg/apis/serving/v1alpha2/framework_xgboost.go, pkg/apis/serving/v1alpha2/kfservice_framework_pytorch.go
Today I investigated the issue #296 , seems that works for last docker image, but the user cannot input the last docker image as `RuntimeVersion must be one of latest`, and `latest` image is not last one.
```
(python36) [root@jinchi1 kfserving]# kubectl create -f /opt/kubeflow/shared/kfserving/docs/samples/pytorch/pytorch.yaml
Error from server: error when creating "/opt/kubeflow/shared/kfserving/docs/samples/pytorch/pytorch.yaml": admission webhook "kfservice.kfserving-webhook-server.validator" denied the request: RuntimeVersion must be one of latest
```
We should add more available images so that user can configure the docker image tag while define the kfservice. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes …
=> add available images to configmap

python/.pylintrc, python/kfserving/kfserving/storage.py, python/kfserving/test/test_s3_storage.py
Previously using storage to download s3 objects, we have to specify the parent key, with this patch it can download files with full path.
```release-note
None
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/302)
=> storage: Allow get s3 object with fully specified path

test/scripts/build-python-image.sh
The CI/CD testing always failed due to #342, logs are as following:
```
Activating service-account
Activated service account credentials for: [kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com]
cp: cannot create regular file ‘Dockerfile’: File exists
```
The problem should be cuased by file conflicts due to multipe components parallel executing in same folder. See details in #342 
Fixes #342 
```release-note
```
---
This change …
=> fix testing problem in building image steps

docs/samples/client/kfserving_sdk_sample.ipynb, python/kfserving/docs/KFServingClient.md, python/kfserving/kfserving/api/kf_serving_client.py, python/kfserving/test/test_kfservice_client.py
The PR is going to add two new APIs:
1. API `promote` to handle promote Canary to Default case.
2. API `Replace` to handle cases that user cannot set the field from existing value to `None` by `patch` API (@yuzisun met that while want to set Canary Spec to None).
The `Replace` called kubernetes API [replace_namespaced_custom_object](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#replace_namespaced_custom_object), instead of  [patch_namespaced_custom_object](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CustomObjectsApi.md#patch_namespaced_custom_object) which is called by `patch` API. The reason is that there is a problem for `patch_namespaced_custom_object` api of kfserving …
=> adding repalce and promote APIs for kfserving sdk

test/README.md
Fix the link to how to install kubebuilder on test/README.md because the current link is not found.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/367)
=> Fix the link to how to install kubebuilder on test/README.md

hack/update-openapigen.sh, pkg/apis/serving/v1alpha2/kfservice_framework_tensorrt_test.go
* Modify sed options in the update-openapigen.sh to run 'make test' on macOS
* I failed to run `make test` on macOS (v10.13.6, High Sierra) with the following error message:
```
$ make test
go generate ./pkg/... ./cmd/...
hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/clientset
Generating listers for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/listers
Generating informers for serving:v1alpha2 at github.com/kubeflow/kfserving/pkg/client/informers
hack/update-openapigen.sh
sed: 1: "pkg/apis/serving/v1alph ...": extra characters at the end of p command
make: *** [generate] Error 1
```
1. I'd appreciate checking …
=> Remove a workaround in the update-openapigen.sh to run 'make test' on macOS

python/kfserving/kfserving/storage.py
Allows using insecure minio storage backend by specifying http as scheme in S3_ENDPOINT environment variable or explicitly by setting USE_SSL to False. Default setting remains secure.
Fixes #361 
```release-note
Allow use of insecure minio storage backend for local development/testing.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> make connection to minio configurable

README.md, docs/DEVELOPER_GUIDE.md
Add instructions on how to install Knative Serving via kubeflow/manifests. The original guide on installing knative v0.9 doesn't work with Kubeflow v0.6.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/359)
=> Update the Knative installation guide

docs/samples/pytorch/README.md, docs/samples/tensorflow/README.md, docs/samples/tensorrt/README.md, test/crds/knative_route.yaml
With latest crd update, status.url has scheme+host format. `Scheme` has to be removed when `SERVICE_HOSTNAME` is populated. 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/255)
=> Updating docs

python/kfserving/kfserving/storage.py, python/kfserving/test/test_s3_storage.py
Bug fix in storage initializer for downloading tensorflow model from s3 storage.
Fixes https://github.com/kubeflow/kfserving/issues/379
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/380)
=> Filter directory keys when downloading models from S3 storage

docs/samples/client/kfserving_sdk_sample.ipynb, python/kfserving/docs/KFServingClient.md, python/kfserving/kfserving/api/kf_serving_client.py
Discussed with @ellis-bigelow and @yuzisun in the PR https://github.com/kubeflow/kfserving/pull/357#discussion_r328163284, adding rollout API to let user easily update the canary traffic percent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/370)
=> add rollout api for SDK

python/kfserving/kfserving/api/kf_serving_client.py
Add an optional parameter to choose KUBECONFIG even when running on k8s.
Currently the code assumes the script using Python SDK will be running in the same cluster as KFServing does.  This will not be true if we use Python SDK in Kubeflow cluster and try to deploy to KFServing in another cluster.  In this case the assumption will break and in-cluster config will not have permission to deploy to KfServing cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/390)
=> add optional param

Makefile
Delete validatingwebhookconfigurations and validatingwebhookconfigurations on `make undeploy` and make `undeploy-dev` to cleanly uninstall kfserving
Fixes #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/392)
=> Cleanly uninstall kfserving in make undeploy and undeploy-dev

pkg/constants/constants.go
This is to reduce default terminationGracePeriod so that user-container
which ignore SIGTERM can be terminated more quickly
Fix #394
If the PR broke initial assumption when deciding the previous default value
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/395)
=> Set KFservice default timeout to lower value

docs/samples/pytorch/README.md, docs/samples/sklearn/README.md, docs/samples/transformer/image_transformer/README.md, docs/samples/xgboost/README.md
Url path in examples are wrong after the v1 protocol change
Fixes #
tested the examples they all work now
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/410)
=> Fix url path in the example

pkg/apis/serving/v1alpha2/explainer.go, pkg/apis/serving/v1alpha2/predictor.go
- Fix kfserving from crashing if spec is invalid
- Add validation for explainer's storage URI
Fixes #396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/406)
=> Refactor ExplainerSpec for better validation

python/kfserving/kfserving/api/kf_serving_watch.py, python/kfserving/setup.py
SDK API with `watch=Ture` cannot get the traffic due to json path is changed in the #420 
And updated the SDK vesion to refresh KFServing SDK in Pypi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/425)
=> enhance sdk due to json path changed

Makefile, config/overlays/test/kustomization.yaml, config/overlays/test/manager_image_patch.yaml, python/kfserving/requirements.txt, test/e2e/test_tensorflow_inference_service.py, test/e2e/utils.py, test/scripts/create-cluster.sh, test/scripts/delete-cluster.sh, test/scripts/run-e2e-tests.sh, test/workflows/components/workflows.libsonnet
Adding E2E test for KFServing. 
My initial thoughts are deploy KFServing and then execute notebook sample, but seems that taks long time. Discussed with @yuzisun , just deploy KFServing and create a sample KFService. 
The E2E case includes:
1. Create a CI/CD cluster;
2. Install istio, knative and KFServing on the cluster;
3. Using python client to create a KFService and ensure that can be started normally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/383)
=> Adding E2E test for KFServing

config/default/configmap/inferenceservice.yaml, install/0.2.0/kfserving.yaml, pkg/apis/serving/v1alpha2/explainer_alibi.go, pkg/apis/serving/v1alpha2/explainer_alibi_test.go, pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go, pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go, pkg/apis/serving/v1alpha2/v1alpha2_suite_test.go
Get validation error when creating the inference service with explainer
```
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Sat, 12 Oct 2019 22:28:00 GMT', 'Content-Length': '217'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \"inferenceservice.kfserving-webhook-server.validator\" denied the request: RuntimeVersion must be one of ","code":400}
```
The alibi key is missing in explainers configmap, it should be 
```json
"explainers": {
"alibi" : {
"image" : "docker.io/seldonio/alibiexplainer",
"defaultImageVersion": "0.2.3",
"allowedImageVersions": [
"0.2.3"
]
}
}
```
**Which issue(s) this PR fixes** *(optional, in `fixes …
=> Fix missing alibi key in explainers configmap

pkg/apis/serving/v1alpha2/explainer_alibi.go, pkg/apis/serving/v1alpha2/framework_pytorch.go, pkg/apis/serving/v1alpha2/framework_scikit.go, pkg/apis/serving/v1alpha2/framework_tensorflow.go, pkg/apis/serving/v1alpha2/framework_tensorrt.go, pkg/apis/serving/v1alpha2/framework_xgboost.go
when I create an inferenceservice including both `explainer` and `predictor`, webhook may reject it with message as below, which is confusing
```
Error from server: error when creating "imagenet.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: RuntimeVersion must be one of 
```
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Detail RuntimeVersion error message

test/e2e/utils.py
fix one e2e test problem
```
name = 'isvc-tensorflow-test', namespace = 'kfserving-ci-e2e-test'
Timeout_seconds = 600
def wait_for_kfservice_ready(name, namespace='kfserving-ci-e2e-test', Timeout_seconds=600):
for _ in range(round(Timeout_seconds/10)):
time.sleep(10)
kfsvc_status = KFServing.get(name, namespace=namespace)
for condition in kfsvc_status['status'].get('conditions', {}):
if condition.get('type', '') == 'Ready':
status = condition.get('status', 'Unknown')
>           if status == 'True':
E           UnboundLocalError: local variable 'status' referenced before assignment
```
Fixes #458 
1. Please confirm that if this PR changes any image versions, then that's the sole …
=> fix one e2e test problem

test/e2e/test_tensorflow_inference_service.py, test/e2e/utils.py
Get more logs for debugging if e2e timeout, for example #454 , the kfserving cannot be started but we cannot get the detail log to investigate. The PR is going to add function to get logs for debugging if inferenceservice started timeout.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/466)
=> Get detailed logs for debugging if e2e timeout

docs/samples/pvc/README.md, docs/samples/pvc/mnist-pvc.yaml, pkg/webhook/admission/pod/storage_initializer_injector.go, pkg/webhook/admission/pod/storage_initializer_injector_test.go, python/kfserving/README.md
The PR is address below items:
1. Added docs for pvc supporting. since someone asked me about how to use model in local (PVC) in KFServing for on-prem cluster, I also did not find the docs, in fact we support the great feature, add related docs. 
2. Add one sample for pvc for on-prem cluster, as @rakelkar commented below.
3. During implement item 2, I found a bug for PVC supporting, the PR fixes that.
Bug: since the init container is linked the model path from source PVC, but the source PVC is not mounted to user container, so that the model cannot be found, as below:
```
2019-10-23 13:13:34.129523: I tensorflow_serving/model_servers/server_core.cc:573]  (Re-)adding model: mnist-sample
2019-10-23 13:13:34.231473: E …
```
=> add docs for pvc supporting

test/scripts/run-e2e-tests.sh
Downgrade istio and knative in e2e tests to see if inferenceservice can be READY normally with below version:
ISTIO: 1.1.6
KNATIVE: 0.8.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/478)
=> Downgrade istio and knative in e2e tests

pkg/apis/serving/v1alpha2/explainer_alibi.go, pkg/apis/serving/v1alpha2/explainer_alibi_test.go, pkg/apis/serving/v1alpha2/framework_custom.go, pkg/apis/serving/v1alpha2/framework_onnx.go, pkg/apis/serving/v1alpha2/framework_onnx_test.go, pkg/apis/serving/v1alpha2/framework_pytorch.go, pkg/apis/serving/v1alpha2/framework_pytorch_test.go, pkg/apis/serving/v1alpha2/framework_scikit.go, pkg/apis/serving/v1alpha2/framework_scikit_test.go, pkg/apis/serving/v1alpha2/framework_tensorflow.go, pkg/apis/serving/v1alpha2/framework_tensorrt.go, pkg/apis/serving/v1alpha2/framework_tensorrt_test.go, pkg/apis/serving/v1alpha2/framework_xgboost.go, pkg/apis/serving/v1alpha2/framework_xgboost_test.go, pkg/constants/constants.go, pkg/controller/inferenceservice/controller_test.go, pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go, pkg/controller/inferenceservice/resources/knative/service_test.go, pkg/webhook/admission/pod/storage_initializer_injector.go, pkg/webhook/admission/pod/storage_initializer_injector_test.go
For now inferenceservice container name is not specified, knative serving will generates the corresponding Pod with a name from `container-name-template` value in ConfigMap config-defaults in knative-serving namespace, which is editable.
For now, inferenceservice webhook mounts volume on the container with hard-code name "user-container", once `container-name-template` changed, inferenceservice cannot work.
so we can add a name to all kinds of component container, not using knative default one.
Fixes #474
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/475)
=> Specify inference server container name

pkg/webhook/admission/pod/mutator.go
Fixes #486
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/488)
=> Ignores pods in mutator that are not managed by kfserving

pkg/apis/serving/v1alpha2/explainer_alibi.go, pkg/apis/serving/v1alpha2/explainer_alibi_test.go
Explainer config is a map and needs consistent ordering when turned into container args otherwise muleiple reconciles will happen causing thrashing of pod creations.
Fixes #489 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/484)
=> Order explainer config in container args

pkg/constants/constants.go, pkg/controller/inferenceservice/controller_test.go, pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go, pkg/controller/inferenceservice/resources/knative/service.go, pkg/controller/inferenceservice/resources/knative/service_test.go
Explanation examples can break due to low revision timeout.
Fixes #490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/491)
=> Configure separate timeouts for Predictor, Transformer and Explainer

python/kfserving/kfserving/storage.py, python/kfserving/test/test_storage.py
We need report error in a consistent way when the storage initializer failed to download the model. Now if the object does not exist, just return successfully.
Fixes #440
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/482)
=> Check whether the storage initilizer really download something

pkg/apis/serving/v1alpha2/inferenceservice_defaults_test.go, pkg/apis/serving/v1alpha2/predictor.go, pkg/apis/serving/v1alpha2/utils.go
Change the default resource to be a map to be extensible in future.
Fixes #496
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/501)
=> Change the default resource to be a map to be extensible in future

pkg/controller/inferenceservice/controller_test.go
Verified the explainer ksvc is created correctly
Then verified the route for explainer is created correctly when status is ready
Fixes #414
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/506)
=> Add test case for endpoint with both predictor and explainer.

pkg/apis/serving/v1alpha2/explainer.go, pkg/apis/serving/v1alpha2/inferenceservice_validation_test.go, pkg/apis/serving/v1alpha2/predictor.go, pkg/apis/serving/v1alpha2/transformer.go, pkg/apis/serving/v1alpha2/utils.go
Now predictor already validate min/max replicas, for transformer and explainer we should do that too.
Fixes #495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/500)
=> Validate replicas for explainer and transformer too

python/alibiexplainer/README.md
Minor changes to fix the link path in explainer doc
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/521)
=> Minor fix of the link path in explainer doc

Dockerfile, executor.Dockerfile
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/507)
=> Add arm64 support for kfserving

README.md, pkg/webhook/admission/pod/mutator.go
The non-kfserving pods going through pod mutator are still calling `getStorageInititalizerConfig`, it should just return if it does not have kfserving label on it.
Fixes #
I also added instruction to add object selector so that pods not managed by kfserving will not go through the kfserving pod mutator.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/531)
=> Move up label check in pod mutator

python/kfserving/requirements.txt, python/kfserving/setup.py
As we have made decision to align SDK version with KFServing release last weekly meeting, I just updated the SDK version. And trying to update in kubeflow-fairing accordingly in https://github.com/kubeflow/fairing/pull/415, but failed in `Travis CI`
```
Installed /home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/minio-5.0.4-py3.7.egg
error: azure-storage-blob 1.5.0 is installed but azure-storage-blob==1.3.0 is required by {'kfserving'}
The command "python setup.py install" failed and exited with 1 during .
```
That's not good to pin version in requirements, that will cause failure during installation, we should avoid that.
Another thing is we need to release new version for SDK, otherwise back fairing integration.
---
This change …
=> update sdk requirements and version

docs/DEVELOPER_GUIDE.md
Add a note to install cluster local gateway for knative 0.9.0+, or there will be [issue](https://github.com/kubeflow/kfserving/pull/524#issuecomment-555433619) when using transformer or explainer.
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/561)
=> Add a note to install cluster local gateway for knative 0.9.0+

Makefile, config/overlays/test/configmap/inferenceservice.yaml
Remove executor in makefile and add logger
Add logger in test configmap since it's already built for that, or will still use the one released
BTW, thought for test we build the newest logger, but I did not see cases for that. Need add e2e test 
for that later.
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/575)
=> Remove executor in makefile and add logger/Add logger test configmap

pkg/webhook/admission/pod/mutator.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/581)
=> Skip get inferenceservice-config configmap for non-kfserving pod

test/scripts/create-cluster.sh, test/scripts/run-e2e-tests.sh
As required in https://github.com/kubeflow/kfserving/pull/586, u pgrade knative to v0.10.0 in CI tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/587)
=> Upgrade knative to v0.10.0 in CI tests

Makefile, hack/update-clusterrolebinding.sh
Consider using `kubectl auth reconcile` for upgrade-safe updating of RBAC objects, to avoid blocking deployment process, which caused by RBAC name changed etc..
Fixes #558
```release-note
NONE
```
UT: PASS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/582)
=> Fix issue of invalid ClusterRoleBinding in developer mode

docs/DEVELOPER_GUIDE.md
Following instruction in https://github.com/kubeflow/kfserving/blob/master/docs/DEVELOPER_GUIDE.md#knative-cli-knctl to compare checksum output of knctl and get following error:
shasum -a 265 ./knctl-*
shasum: Unrecognized algorithm
Type shasum -h for help
265 is incorrect which cause this error.  Use this PR to correct this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/593)
=> correct shasum algorithm

pkg/apis/serving/v1alpha2/framework_tensorrt.go, pkg/apis/serving/v1alpha2/framework_tensorrt_test.go
Container port specified with logger will not work. For built in frameworks it's always 8080 so we need not specify it. For custom spec the correct solution would be issue #594 
Fixes #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/595)
=> Tensorrt  specified container port, which will not work with logger 

python/kfserving/kfserving/storage.py
There are currently issues reported when public S3 buckets are being requested (especially when no default AWS_ENDPOINT is provided). These issues appear in the form of " string index out of range".
This can be addressed in the python library by providing a default S3 bucket, in this case "s3.amazonaws.com", which is the default that will allow access to public S3 buckets without the need to provide any credentials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/589)
=> Added default amazon endpoint to support standard AWS endpoints by default (and public buckets)

docs/samples/onnx/README.md, docs/samples/pytorch/README.md, docs/samples/sklearn/README.md, docs/samples/tensorflow/README.md, docs/samples/tensorrt/README.md, docs/samples/xgboost/README.md
Following instruction in https://github.com/kubeflow/kfserving/tree/master/docs/samples/tensorflow and found the following links are broken/incorrect:
- "allow Google Cloud Storage"  --> 404
- "Knative CLI (knctl)" -> back to same/current page
Use this PR to correct these links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/599)
=> Fix links in KFServing Tensorflow sample

.gitignore, config/overlays/development/configmap/ko_resolve_logger, config/overlays/development/kustomization.yaml, docs/DEVELOPER_GUIDE.md, hack/image_patch_dev.sh
Enhance "make deploy-dev" to also use logger image built by user.
Fixes #572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/573)
=> enhance make deploy-dev to also include logger image

pkg/controller/inferenceservice/resources/knative/service.go
Currently queue-proxy cpu limit is set too small(40m) and affects performance when doing load testing with sklearn example using following command. 
```
hey -z 300s -c 30 -m POST -host "sklearn-iris.default.example.com" -H "Content-Type: application/json" -D ./input.json "http://localhost:8080/v1/models/sklearn-iris:predict"
``` 
The average latency goes up to 100ms despite the actual prediction only takes 1ms.
Fixes https://github.com/kubeflow/kfserving/issues/606
After the fix the latency is now average 5ms as expected.
```release-note
``` …
=> Set queue proxy limit to 20% resource of main container

docs/samples/autoscaling/README.md, docs/samples/pvc/README.md
1. broken link in Autoscaling sample https://github.com/kubeflow/kfserving/tree/master/docs/samples/autoscaling
Under "Setup" #3
...allow Google Cloud Storage (-> https://knative.dev/docs/serving/outbound-network-access/ -> 404)
This should be fixed  in https://github.com/kubeflow/kfserving/pull/599, but unfortunately, we have missed this one at that time.
2. typo in PVC sample
https://github.com/kubeflow/kfserving/tree/master/docs/samples/pvc
Under " Create the InferenceService"
Update the ${PVC_NAME} to the created PVC name in the **mnis-pvc.yaml** and apply:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/617)
=> Fix broken link in KFServing Autoscaling sample and typo in PVC sample

.gitignore, Makefile, config/overlays/dev-image-config/kustomization.yaml, docs/DEVELOPER_GUIDE.md, hack/alibi_patch_dev.sh, hack/misc_patch_dev.sh, hack/model_server_patch_dev.sh
In roadmap there's
```
* Automated Image Injection for Model Servers.
* Implement new developer commands to deploy kfserving with local images.
```
Fixes #590 
- Use KO_DOCKER_REPO to push the image
- Always use latest as the version
- Support only one model sever each time, after apply other model servers will be deleted from configmap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/591)
=> Enable make to apply local changes of model servers, explainer and storage-initializer

docs/samples/transformer/image_transformer/setup.py
transformer e2e is broken in CI with following error, since `PILLOW_VERSION` is removed in 7.0(https://github.com/python-pillow/Pillow/issues/4130)
```
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/image_transformer/__main__.py", line 17, in <module>
from .image_transformer import ImageTransformer
File "/image_transformer/image_transformer.py", line 18, in <module>
import torchvision.transforms as transforms
File "/usr/local/lib/python3.7/site-packages/torchvision/__init__.py", line 4, in <module>
from torchvision import datasets
File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/__init__.py" …
```
=> pin pillow version to 6.1

python/kfserving/README.md, python/kfserving/docs/KFServingClient.md, python/kfserving/kfserving/api/kf_serving_client.py, python/kfserving/kfserving/constants/constants.py, test/e2e/common/utils.py, test/e2e/predictor/test_sklearn.py, test/e2e/predictor/test_tensorflow.py, test/e2e/predictor/test_xgboost.py, test/e2e/transformer/test_transformer.py
Got feedback, Need API in KFServing Python SDK Client to quick check the KFServing status and has ability to wait for the inferenceservice ready, and then user can do following things once ready. In fact there is same function in test utils.  The PR is going to add below two APIs and update tests.
- wait_for_ready:  Wait for the InferenceService ready
- is_isvc_ready: Quick way to check if the InferenceService is ready
Fixes #609  …
=> add APIs to wait for isvc ready and check status

python/xgb.Dockerfile
Recent pip release 20.x breaks a lot of the python wheels including xgboost (https://github.com/dmlc/xgboost/issues/5221), need to fallback to 19.x for now.
Fixes #639
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/641)
=> Use pip 19.3.1 instead of 20.x for installing xgboost wheel

pkg/apis/serving/v1alpha2/transformer.go, pkg/controller/inferenceservice/resources/knative/service.go
Add storage uri for transformer to inject the storage initializer, the use case here is to download a vocabulary file from cloud storage for bert tokenization.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/643)
=> Add storage uri for transformer

Dockerfile, pkg/constants/constants.go, pkg/webhook/admission/pod/logger_injector.go, pkg/webhook/admission/pod/mutator.go, pkg/webhook/admission/pod/storage_initializer_injector.go
This PR implements 2 changes (please let me know if you want them as separate PRs)
1. Switch from `klog` to make logging consistent and add descriptive logging messages when mutator fails to make debugging of issues easier
If there is a problem with parsing the resources from the ConfigMap, it will produce error messages like
```
{"level":"error","ts":1576664278.7646105,"logger":"inferenceservice.kfserving-webhook-server.pod-mutator","msg":"Failed to mutate pod","name":"sklearn-iris-predictor-default-pvpmm","error":"Failed to parse resource configuration for \"storageInitializer\": \"quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'\""
```
2. Initialize `securityContext` for injected containers. Current …
=> Initialize SecurityContext in injected containers and improve logging

test/e2e/common/utils.py
Currently, when running test_sklearn.py, test_tensorflow.py, test_xgboost.py, test_transformer.py in an environment without ext loadbalancer, it fails with :
_>       cluster_ip = service.status.load_balancer.ingress[0].ip
E       TypeError: 'NoneType' object is not subscriptable_
[As load balancer is not required](https://github.com/kubeflow/kfserving/issues/629#issuecomment-578401707), will use this PR to enable these to run in an environment w/o ext loadbalancer.
Fixes #
1. Please confirm that if this PR changes any image versions, then that's the sole …
=> Enabled test_sklearn.py, etc. to run in an env without ext load balancer

test/e2e/predictor/test_tensorflow.py
Currently, there is a residual inferenceservice isvc-tensorflow after running test_tensorflow.py. Running test_tensorflow.py again will hit the following error : 
`E           HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"inferenceservices.serving.kubeflow.org \"isvc-tensorflow\" already exists","reason":"AlreadyExists","details":{"name":"isvc-tensorflow","group":"serving.kubeflow.org","kind":"inferenceservices"},"code":409}`
Use this PR to delete the residual inferenceservice.
Fixes #
1. Please confirm …
=> Delete isvc-tensorflow inferenceservices after testing

docs/samples/transformer/image_transformer/README.md
In https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer
Under **Setup** # 3
Your cluster's Istio Egresss gateway must [allow Google Cloud Storage](https://knative.dev/docs/serving/outbound-network-access/)
--> follow link -- > 404
This should be fixed in [PR599](https://github.com/kubeflow/kfserving/pull/599), but unfortunately, we have missed this one at that time.
Fixes #
```release-note
```
--- …
=> Fixed broken link in transformer sample

python/kfserving/kfserving/api/creds_utils.py
For some case, user cannot get configmap from other namespace, if so we should allow user get the data key from constants.
Fixes #693 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/701)
=> enhance creds if cannot get data secret data key from configmap

hack/python-sdk/client-gen.sh
I was working on the python sdk and discovered that the central maven link is no longer available. Thus, we replace it with the search maven link.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/711)
=> Fix broken link for python client gen script

docs/samples/pytorch/README.md, docs/samples/xgboost/README.md
Endpoint in kfserver changed to include v1. Updated example to reflect the api change.
Example README for xgbserver and pytorch is outdated.
Updated to v1/ for the new endpoint. 
Fixes #
No
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/716)
=> Update example usage in README

docs/samples/pvc/README.md
In the kfserving PVC examples, we mentioned training model and store into PVC by following kubeflow/examples mnist example, recently the mnist example has been updated removed related parts. The PR is going to update readme to reasonable place for training and store model to PVC and then using KFServing to deploy InferenceService.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/713)
=> Update pvc example accordingly

python/kfserving/kfserving/api/creds_utils.py, python/kfserving/test/test_cred_utils.py, python/kfserving/test/test_creds_utils.py
There is a minor bug in python library, the check_sa_exists function does not check the last service account that the api returns.
Fixes #
```release-note
Fixed bug in python library that was trying to recreate an existing service account
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/718)
=> Fix check_sa_exists not checking all service accounts in python library

docs/predict-api/v2/required_api.md
In parameters a string value should be an actual string, not a
collection of arbitrary bytes. So change the GRPC type from "bytes" ->
"string".
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kfserving/735)
=> [Predict Protocol V2] Change type for GRPC string parameter to 'string'

config/default/webhook/manifests.yaml, install/v0.3.0/kfserving.yaml
There are typos in MutatingWebhookConfiguration. I found it while patching.
Fixes #
```release-note
```
=> Fix MutatingWebhookConfiguration typo

Makefile, config/default/kustomization.yaml, config/default/manager_resources_patch.yaml, docs/DEVELOPER_GUIDE.md
Allow configurable CPU and memory limits for the controller manager before deploying.
This PR causes minimal change to the current deploy process with a Makefile. To use this new **optional** addition, simply set environment variables, `CPU_LIMIT` and `MEMORY_LIMIT`. Or run make targets with those variables specified, e.g.
```
make deploy CPU_LIMIT=800m MEMORY_LIMIT=2000Mi
```
Fixes #681
```release-note
NONE
```
---
This change is [<img …
=> Configure memory

docs/samples/custom/kfserving-custom-model/kfserving_sdk_custom_image.ipynb
Adds a note in the custom sample jupyter notebook about using `kfserving-ingressgateway` vs `istio-ingressgateway` when running a prediction. 
**Which issue(s) this PR fixes** 
Related to #748
=> Allow kfserving-ingressgateway in custom sample notebook

docs/samples/explanation/alibi/imagenet/README.md, docs/samples/explanation/alibi/imagenet/imagenet.yaml
When trying to run the imagenet sample, I encountered the issues below which generate errors when executing the command `kubectl create -f imagenet.yaml` : 
- A typo in the documentation : INGRESS_GATEWAY is a variable 
- the inferenceservice must be deployed in the <user_namespace>  instead of  the default namespace 
Fixes #
=> Errors when running imagenet sample

python/pytorch.Dockerfile
```
Step 4/14 : RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-4.2.12-Linux-x86_64
.sh  &&      chmod +x ~/miniconda.sh &&      ~/miniconda.sh -b -p /opt/conda &&      rm ~/miniconda.sh &&
/opt/conda/bin/conda install conda-build &&      /opt/conda/bin/conda create -y --name pytorch-py37 python=
3.7.3 numpy pyyaml scipy ipython mkl &&      /opt/conda/bin/conda clean -ya
---> Running in 03b22fce0166
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
/bin/sh: 1: /opt/conda/bin/conda: not found
```
Looks the link is moved and returning 301 and curl does not follow the redirect, add `-L` to fix the issue.
**Which issue(s) this PR fixes** *(optional, in …
=> Fix miniconda installation in pytorch dockerfile

prow_config.yaml
This script has been moved to a new location.
Fixes #
```release-note
NONE
```
=> Fix the link to run_e2e_workflow.py script

Makefile, config/overlays/development/kustomization.yaml
`make deploy-dev` will fail because `config/overlays/development` is missing `manager_auth_proxy_patch.yaml`. Makefile should copy the patch file from `config/default`
Fixes #779
```release-note
NONE
```
=> fix missing patch file in config/overlays/development

CONTRIBUTING.md
Slack link in CONTRIBUTING.md only allows people with a `@google.com`, `@caicloud.io`, or `@microsoft.com` email address to sign up.
Update the link with link from kubeflow.org which allows anyone to sign up.
=> Use public slack link

config/default/configmap/inferenceservice.yaml, python/kfserving/kfserving/constants/constants.py
...and added support for TensorFlow Serving versions 2.0.0 and 2.1.0
This makes two small changes to the default config:
1. The default names used for the variables that store S3 credentials deviate from the convention that is normally followed, leading to confusion when interacting with KFServing. Currently it expects
awsAccessKeyID and awsSecretAccessKey. This PR changes that to AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.
Fixes #696 
Will probably need to update a few examples to reflect the change
None
---
This change is [<img …
=> Updated S3 credential variable names to commonly used en var names

docs/samples/xgboost/README.md
Cleanup xgboost sample instructions. Removal of `xgbserver` dependency to train&save a model or invoke the inference endpoint.
`xgbserver` is used by `inferenceservice` to serve a saved model, we should not expect data scientists to have it installed in their environment.
=> cleanup xgboost sample

docs/samples/README.md, docs/samples/bentoml/README.md, docs/samples/bentoml/bentoml.yaml
**What this PR does / why we need it:**
Add a custom inference sample using [BentoML](https://bentoml.org) to the documentation.
This example shows KFServing users how to use BentoML to quickly deploy a model server as KFServing InferenceService.
=> Add custom inference example using BentoML

test/scripts/run-e2e-tests.sh, test/scripts/sdk-test.sh, test/workflows/components/workflows.libsonnet
I updated the test-worker image that's used Python 3.8, and removed some code that upgrading Python from 3.5 to 3.6 in test script. Thanks.
Fixes #813
=> Upgrade test-worker to use new Python for testing

python/kfserving/kfserving/storage.py
Configuration region-name to avoid get_bucket_location API calls, some users
may have restricted policies, thus allow for these situations. 
Fixes #
```release-note
```
=> allow configurable region name

docs/samples/istio-dex/README.md
Documents an easier method to obtain Dex authentication token by using browser cookies.
=> Add an easier method to obtain Istio-Dex authentication token

python/kfserving/kfserving/storage.py
Fixes #632
When urlparse is called on "s3.amazonaws.com", it's prased as "path" not as "netloc" resulting in an error where hostname is not provided. By adding the prefixed http, the url now stores the "s3.amazonaws.com" in its "netloc" instead of the "path" and works as expected.
=> Added prefixing http for the fix to work

pkg/controller/inferenceservice/resources/knative/service.go
The Parallelism field introduced with #637 sets the KNative autoscaler annotation. It does however not set the KNative `ContainerConcurrency` field, which means that the logic in `queue-proxy` is mostly bypassed. It never manages timeouts nor the connection queue. This has a number of drawbacks:
1) The serving instance will receive all connections directly, and will not handle timeouts and queueing as gracefully as one wants (or at all).
2) The load balancing function of KNative Activator does not work as intended. Instead of intelligently directing requests to Pods that have resources available, it will emit them randomly. See https://github.com/knative/serving/issues/7792#issuecomment-622285173 for more detail.
KNative Activator, when correctly …
=> Set ContainerConcurrency to Parallelism

README.md
Update test KFServing installation documentation with the following changes:
1. Avoid using namespace with control panel label and use a dedicated namespace for inferenceservice test
2. Kubectl command to Fetch hostname to be used in the header curl since hostname consists namespace (sklearn-iris.default.example.com) it might be misleading to document it explicitly since users might use other namespaces than default
Fixes # …
=> Update test KFServing installation documentation

docs/apis/README.md, docs/predict-api/v2/required_api.md, docs/samples/azure/README.md, docs/samples/triton/simple_string/README.md, docs/samples/triton/simple_string/triton.yaml, python/kfserving/README.md, python/kfserving/test/test_azure_storage.py, test/e2e/predictor/test_triton.py
=> Triton naming

python/alibiexplainer.Dockerfile, python/alibiexplainer/setup.py, python/pytorch.Dockerfile
Fixes #859
This is a fix to v0.3.0 branch as the original code built from master alibi repo. When we did v0.3.0 image build in March this year the image created for alibiexplainer was not compatible.
We could retag a new image for alibiexplainer 0.3.0 from this fix to branch?
=> Alibi explainer fix

pkg/apis/serving/v1alpha2/inferenceservice_status.go, pkg/controller/inferenceservice/controller.go, pkg/controller/inferenceservice/controller_test.go, pkg/controller/inferenceservice/reconcilers/knative/service_reconciler.go, pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go
Adds logic to record events when the `InferenceService` moves from 
`non-Ready --> Ready`
and 
`Ready --> non-Ready`
Fixes #881 
```release-note
Record Events when InferenceService goes in and out of readiness
```
=> Record Events when InferenceService goes in and out of readiness

docs/samples/drift-detection/alibi-detect/cifar10/README.md, docs/samples/drift-detection/alibi-detect/cifar10/cifar10_drift.ipynb, docs/samples/outlier-detection/alibi-detect/cifar10/README.md, docs/samples/outlier-detection/alibi-detect/cifar10/cifar10_outlier.ipynb, go.mod, go.sum, pkg/logger/worker.go
Fixes #885 
* Updates logger to use V1 CloudEvents protocol
* Updates libraries to include latest CloudEvents sdk inline with KNative Eventing.
* Updates examples for drift/outlier detection to suggest KNative Eventing >= 0.14.2
=> Update to CloudEvents V1 protocol

Makefile, config/default/manager/manager.yaml, config/default/webhook/manifests.yaml, config/overlays/development/configmap/ko_resolve_logger, go.mod, hack/quick_install.sh, test/scripts/run-e2e-tests.sh
Fixes #891 
a couple of markers are generated by `controller-gen` but it is only supported by kubernetes 1.16 and 1.17, so we need to add `--validate=false` for installing KFServing on kubernetes 1.15.
https://kubernetes.io/docs/reference/using-api/api-concepts/#merge-strategy
```release-note
KFServing now minimally requires kubernetes 1.15 to use the object selector for pod mutator
```
=> Move KFServing to minimally require kubernetes 1.15

python/kfserving/kfserving/api/kf_serving_watch.py
Sometimes, there is a traceback while watching a created inferenceservice. see #884 for details, the PR is going to enhance watch API to avoid that, even if that cannot be 100% reproduced.
Fixes #884 
```release-note
```
=> Enhance SDK watch API to avoid traceback

README.md, docs/samples/sklearn/perf.yaml
Fix the Test KFServing Installation in the main README
- In order to run `port-forward` and the rest of the commands in the same shell, port-forward needs to run as background process.
- Run perf.yaml under the same testing namespace
- Update perf.yaml payload to the testing namespace and add `restartPolicy` to fix the below bug https://github.com/kubernetes/kubernetes/issues/41194
```
The Job "load-test284zn" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Always": supported values: "OnFailure", "Never"
```
```release-note
```
=> Fix Test KFServing Installation in the main README

docs/samples/custom/customized-urls/Dockerfile, docs/samples/custom/customized-urls/Readme.md, docs/samples/custom/customized-urls/app.py, docs/samples/custom/customized-urls/customized-urls.yaml, pkg/controller/inferenceservice/controller_test.go, pkg/controller/inferenceservice/resources/istio/virtualservice.go, pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Fix #733
In some situations, you may have a `custom model image` but can not modify its server routes, this server may also have one or more predict endpoints. Here is a simple sample to show how to deploy this custom service.
* `app.py` is a simple flask server, it has two endpoints: `customized_urls_test` and `hello_world`
```python
import os
from flask import Flask
app = Flask(__name__)
@app.route('/customized/urls/demo/test/1')
def customized_urls_test():
target = os.environ.get('TARGET', 'World')
return 'Hello {}. Func customized_urls_test is called!\n'.format(target)
@app.route('/v1/models/customized-sample:predict')
def hello_world():
target = os.environ.get('TARGET', 'World')
return 'Hello {}!\n'.format(target)
if __name__ == "__main__": …
```
=> add customized urls and sample

pkg/controller/inferenceservice/controller_test.go
When run `make test` to test the UT, found this check is not stable, the result look like random. I am not sure why this check is not stable. So remove this check until we figure out why.
`controller_test.go:TestInferenceServiceWithOnlyPredictor`
```
g.Eventually(func() bool {
isvc := &kfserving.InferenceService{}
err := c.Get(context.TODO(), serviceKey, isvc)
if err != nil || isvc.Status.GetCondition(apis.ConditionReady) == nil {
return false
}
if isvc.Status.GetCondition(apis.ConditionReady).Status ==
v1.ConditionTrue {
return true
}
return false
}, timeout).Should(gomega.BeTrue())
```
=> remove the unstable check 

pkg/controller/inferenceservice/controller_test.go, pkg/controller/inferenceservice/resources/istio/virtualservice.go, pkg/controller/inferenceservice/resources/istio/virtualservice_test.go
Currently, the retires in the VirtualService are setup to retry three times on all errors. KNative will also retry three times on all errors between a Transformer and Predictor. These settings, combined with default high timeouts can easily lead to a self-DDoS in an overload condition. See screenshot.
KNative has removed the retries in their VirtualServices: https://github.com/knative/serving/issues/6549#issuecomment-623800315
KFserving should do one of the following:
1) Disable retries completely (which is what this PR does)
2) Allow retries, but not on the 502/504 that are thrown on timeouts. Retrying on `connect-failure` should be safe.
3) Make the behavior configurable, as users might have different requirements for if they want KFServing to …
=> Disable retries in Istio VirtualService

docs/samples/custom/grpc-server/README.md, docs/samples/custom/grpc-server/grpc-service.yaml
update custom/grpc-service sample
* add custom.container.name field to slove the error
`ValidationError(InferenceService.spec.default.predictor.custom.container): missing required field "name" in org.kubeflow.serving.v1alpha2.InferenceService.spec.default.predictor.custom.container`
* change the way of `Get the inference service address:`.
`kubectl get inferenceservice grpc-service` instead of `kubectl get ksvc grpc-service-predictor-default`
=> update custom/grpc-service sample

config/configmap/inferenceservice.yaml, config/overlays/test/configmap/inferenceservice.yaml, docs/samples/logger/basic/README.md, pkg/constants/constants.go, pkg/webhook/admission/pod/logger_injector.go
fixes https://github.com/kubeflow/kfserving/issues/836
Don't need to set namespace in the url as the short-form url 'default-broker' will find current namespace. To hit a specific namespace the env var could be set to 'default-broker.specificnamespace'
Parallel to https://github.com/SeldonIO/seldon-core/pull/1861
=> make default req log url more flexible

pkg/apis/serving/v1alpha2/framework_custom.go
Fixes #937 
add custom default conainer name for resolve the `ValidationError`.
```
ValidationError(InferenceService.spec.default.predictor.custom.container): missing required field "name" in org.kubeflow.serving.v1alpha2.InferenceService.spec.default.predictor.custom.container
```
=> add custom default conainer name

tools/tf2openapi/Dockerfile
- The triggered build for tf2openapi has been failing recently after migrating to go module
Fixes #
```release-note
```
=> Fix tf2openapi dockerfile

pkg/apis/serving/v1alpha2/framework_tensorflow.go, pkg/apis/serving/v1alpha2/framework_tensorflow_test.go, pkg/constants/constants.go, pkg/controller/inferenceservice/controller_test.go, pkg/controller/inferenceservice/reconcilers/knative/service_reconciler_test.go, pkg/controller/inferenceservice/resources/knative/service_test.go
TensorFlow can in some cases, at least on GPU, end up in a OOM condition at runtime that it never recovers from. This means that each request to the predictor ends up failing. We're observing this sporadically with the 11B T5 model on 16GB GPUs. This shouldn't really happen, but something inside either the model or TensorFlow after several hours of runtime can decide to allocate more input tensors than there is GPU memory.
To manage this, a `LivenessProbe` is added on the Tensorflow Predictor. The probe is fairly generous, requiring three consecutive failures 10 seconds apart.
A constant for the `InitialDelaySeconds` is defined and set to 180s. This is longer than KNative allows a revision to deploy in KNative < …
=> Add LivenessProbe to Tensorflow Predictor

ADOPTERS.md
Update to add Max Kelsen to Adopters file. Max Kelsen is currently using KFserving to support a number of production workloads.
=> Add Max Kelsen to ADOPTERS.md

pkg/controller/inferenceservice/resources/knative/service.go
As described in #962. The `minScale` annotation is never set to 0 when updating an existing `InferenceService`'s `minReplicas` from a positive number to zero. This will give the user the impression of scale-to-zero not working, and leave the KFServing administrator pulling his hair trying to figure out how KNative scale to zero can be broken for only this specific `InferenceService`.
**Which issue(s) this PR fixes**
Fixes #962
```release-note
Fixes a bug where enabling Scale-To-Zero on an existing InferenceService did not take effect.
```
=> Update KNative annotation when modifying minReplicas to 0

README.md, docs/samples/autoscaling/README.md, docs/samples/batcher/basic/README.md, docs/samples/bentoml/README.md, docs/samples/custom/hello-world/README.md, docs/samples/custom/kfserving-custom-model/README.md, docs/samples/custom/prebuilt-image/README.md, docs/samples/gcp-iap/README.md, docs/samples/kafka/README.md, docs/samples/onnx/README.md, docs/samples/pytorch/README.md, docs/samples/rollouts/README.md, docs/samples/s3/README.md, docs/samples/sklearn/README.md, docs/samples/tensorflow/README.md, docs/samples/transformer/image_transformer/README.md, docs/samples/triton/bert/README.md, docs/samples/triton/simple_string/README.md, docs/samples/xgboost/README.md
- Update ingress gateway access instruction
- Add badges for go coverage, report card and slack invite.
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #1005 #982
=> Update ingress gateway access instruction and add KFServing repo badges

pkg/apis/serving/v1beta1/component.go, pkg/apis/serving/v1beta1/explainer.go, pkg/apis/serving/v1beta1/explainer_alibi.go, pkg/apis/serving/v1beta1/explainer_alibi_test.go, pkg/apis/serving/v1beta1/explainer_custom.go, pkg/apis/serving/v1beta1/explainer_custom_test.go, pkg/apis/serving/v1beta1/inference_service.go, pkg/apis/serving/v1beta1/inference_service_defaults.go, pkg/apis/serving/v1beta1/inference_service_validation.go, pkg/apis/serving/v1beta1/inference_service_validation_test.go, pkg/apis/serving/v1beta1/predictor.go, pkg/apis/serving/v1beta1/predictor_custom.go, pkg/apis/serving/v1beta1/predictor_custom_test.go, pkg/apis/serving/v1beta1/predictor_onnxruntime.go, pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go, pkg/apis/serving/v1beta1/predictor_sklearn.go, pkg/apis/serving/v1beta1/predictor_sklearn_test.go, pkg/apis/serving/v1beta1/predictor_tfserving.go, pkg/apis/serving/v1beta1/predictor_tfserving_test.go, pkg/apis/serving/v1beta1/predictor_torchserve.go, pkg/apis/serving/v1beta1/predictor_triton.go, pkg/apis/serving/v1beta1/predictor_triton_test.go, pkg/apis/serving/v1beta1/predictor_xgboost.go, pkg/apis/serving/v1beta1/predictor_xgboost_test.go, pkg/apis/serving/v1beta1/transformer.go, pkg/apis/serving/v1beta1/transformer_custom.go, pkg/apis/serving/v1beta1/transformer_custom_test.go, pkg/utils/utils.go
Fast follow from Dan's v1beta1 PR.
1. Cleaned up GetComponent() validation and accessor logic.
2. Broke apart Component and Implementation abstraction from a dual purpose Component abstraction.
3. Abstracted validation logic to the ComponentImplementation level, rather than both Component and Implementation.
4. Added Validation/Defaulting extension points per Component
5. Automated error messages for one-of semantic ```Exactly one of [SKLearnSpec, XGBoostSpec, TFServingSpec, TorchServeSpec, TritonSpec, ONNXRuntimeSpec, CustomPredictor] must be specified in PredictorSpec```
6. GetContainer now takes the full extension spec instead of just containerconcurrency.
=> Genericized component logic; cleaned up valdation and other interfaces

docs/samples/s3/README.md
Kubeflow manifests repository's master branch is configured with KFServing version 0.3. And current kfserving s3 sample document is working with KFServing version 0.4 but not with before version 0.3. So, I would like to supply additional configuration information with this PR. 
Fixes #None
None
```release-note
```
=> Add S3 access key format for prior version of KFServing

python/alibiexplainer/alibiexplainer/__main__.py, python/alibiexplainer/alibiexplainer/explainer.py, python/alibiexplainer/setup.py, python/kfserving/kfserving/handlers/http.py, python/kfserving/kfserving/kfmodel.py, python/kfserving/test/test_server.py
This is a re-open of #791. Please check discussion in #791.
Requests from KFServer are currently block. This leads to a transformer not being able to make more than number of Tornado workers concurrent requests to the predictor.
As predictors are usually the bottleneck, and transformers are fast, the transformer becomes an unnecessarily bottleneck.
This PR applies Tornado best practices, making HTTP requests async. This drastically improves the transformer performance.
**Before**
Here we scale transformer instances with 40 worker threads each, to handle a total of 300 requests
**After**
On one transformer instance, with 1 thread. The target number of concurrent requests is much quicker achieved on the predictor, while consuming less resources. …
=> Make KFServer HTTP requests asynchronous

config/overlays/development/configmap/ko_resolve_batcher
During build there's message like:
```
➜  kfserving git:(master) ✗ make deploy-dev
/Users/pugang/go/bin/controller-gen "crd:maxDescLen=0" paths=./pkg/apis/serving/v1alpha2/... output:crd:dir=config/crd
/Users/pugang/go/bin/controller-gen rbac:roleName=kfserving-manager-role paths=./pkg/controller/inferenceservice/... output:rbac:artifacts:config=config/rbac
.....................................
2020/09/02 15:34:34 Publishing docker.io/pugang/logger-254effe41b2d12817e512614f7349610:latest
2020/09/02 15:40:55 Published docker.io/pugang/logger-254effe41b2d12817e512614f7349610@sha256:e593d7a8f7d4cbc0b2640342a672bfbfbf8d8dcc5db18670cdcda60638015cf2
2020/09/02 15:40:56 NOTICE!
-----------------------------------------------------------------
We will start …
```
=> Add the ko prefix to prevent the notice message during building

python/alibiexplainer/alibiexplainer/__main__.py, python/kfserving/kfserving/kfserver.py
#983 got merged while me and @yuzisun were nailing down the sporadic build issues. There seems to be a lot of situations where multi process workers break with Tornado in Python 3.5+ due to asyncio not being thread (process) safe. These issues are realized with the async-mangling needed to get the synchronous Alibi implementation to work with the now async KFServer.
The recommendation from the Tornado team seems to be to run only one process and handle load balancing elsewhere. Instead of making that change, as I do not know what impact it would have on other usages of KFServer I'm trying to shift the IOLoop and process fork order to make sure all IOLoop actions happen after the fork.
=> Fix thread safety issue in KFServer asyncio

OWNERS
As suggested by @ellistarn in https://github.com/kubeflow/kfserving/pull/1069#issuecomment-685274886. Adding myself as reviewer, primarily for adding `ok-to-test` labels on my own PRs and from my (forthcoming) team.
Org member PR: https://github.com/kubeflow/internal-acls/pull/336
=> Add Peter Salanki as reviewer

cmd/agent/main.go, pkg/agent/downloader.go, pkg/agent/puller.go, pkg/agent/syncer.go, pkg/agent/watcher.go
Follow-on changes to #989 based on remaining review suggestions.
- Simplified configmap change diffing
- Connect watcher and puller with event channel
- Have puller track in-progress ops per model via op completion channel and tie lifecycle of per-model channel+goroutine pairs to this
=> Puller streamlining/simplification

pkg/apis/serving/v1alpha2/framework_onnx.go, pkg/apis/serving/v1alpha2/framework_onnx_test.go
Add the support for parsing the `storageUri` in an `InferenceService` CRD to take in a generic filename such that the below:
```yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
name: onnx-from-uri
spec:
default:
predictor:
onnx:
storageUri: s3://some_bucket/some/key/path/my_great_model.onnx
```
will also be valid. Here, if the path does not specify a file name, e.g. `s3://some_bucket/some/key/path`, then we'd continue to use the default `model.onnx`.
Fixes #1004 
1. Please confirm that if this PR changes any image versions, then …
=> support generic filename for ONNX runtime model (#1004)

python/kfserving/kfserving/kfserver.py
KFServer uses the number of cores on the machine to set the number of process in its tornado service which can delay the initialization time and increase the memory usage a lot.
A local testing suggests that KFServer loaded 64 processes and used more than 500Mb for a simple SKLearn model. Once I set the worker number to 1, the memory usage was reduced to around 100Mb. 
```
[I 200927 18:26:06 kfserver:88] Registering model: mlguild-iris-svm
[I 200927 18:26:06 kfserver:77] Listening on port 8080
[I 200927 18:26:06 kfserver:79] Will fork 0 workers
[I 200927 18:26:06 process:126] Starting 64 processes
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
=> Set KFServing default worker to 1

docs/apis/README.md, docs/predict-api/v2/README.md, docs/samples/triton/bert/bert_tokenizer/Dockerfile, pkg/apis/serving/v1alpha2/framework_triton.go, pkg/apis/serving/v1alpha2/inferenceservice_types.go, pkg/apis/serving/v1alpha2/openapi_generated.go, pkg/apis/serving/v1alpha2/swagger.json, pkg/apis/serving/v1beta1/predictor.go, python/kfserving/docs/V1alpha2PredictorSpec.md, python/kfserving/kfserving/models/v1alpha2_predictor_spec.py
The Github repo was updated recently, so this PR updates the references so as to not rely on redirects.
https://github.com/NVIDIA/triton-inference-server -> https://github.com/triton-inference-server/server
=> Update Triton repo links

docs/DEVELOPER_GUIDE.md
Adds the instruction from #977 to the developer guide, so people with that problem will find it easier to update their `controller-gen` when that error occurs.
=> Add instruction from #977 to the developer guide

docs/samples/pytorch/README.md
When invoking pytorchserver as a module locally, the symlink for the `model_dir` works only with absolute path, so I've updated the related documentation sample.
Fixes #1116
=> Correction for the sample invocation of pytorchserver

config/rbac/role.yaml, pkg/controller/v1alpha2/inferenceservice/controller.go, pkg/controller/v1beta1/inferenceservice/controller.go
This is an additional change needed for Openshift clusters. With Kfserving 0.4, I get the same issue mentioned in #1035 even with the changes made in https://github.com/kubeflow/kfserving/pull/1122 . Seems like one more finalizer needed permission as adding the line in this PR allowed successful InferenceService creation.
Fixes #1035
```release-note
Add inferenceservices/finalizers RBAC rules to fix failing InferenceService creation
```
=> Add inferenceservice finalizer rbac rules

pkg/apis/serving/v1alpha2/framework_onnx.go, pkg/apis/serving/v1alpha2/framework_onnx_test.go
Fixes a conditional for ONNX storage URI validation.
Fixes #
```release-note
```
=> fix conditional in ONNX storage URI validation

docs/DEVELOPER_GUIDE.md
The Makefile requires yq to deploy, so this just adds it as a dep.
=> Add yq as dep in developer guide 

config/crd/kustomization.yaml, config/crd/patches/protocol.yaml, docs/samples/custom/prebuilt-image/custom.yaml, docs/samples/v1beta1/custom/simple.yaml, docs/samples/v1beta1/tensorflow/grpc.yaml
Add protocol as required. CRDs are updated accordingly too.
Notice we must add "preserveUnknownFields=false" to spec or another error will be reported, see kubernetes-sigs/controller-tools#476
Fixes #1070
=> Support Kubernetes 1.18

config/crd/kustomization.yaml, config/crd/patches/protocol.yaml, docs/samples/custom/prebuilt-image/custom.yaml
This PR cherrypicks a yaml fix commit (#1128). This is a yaml only change.
=> Cherry-pick of 'Support Kubernetes 1.18' (#1128) to release-0.4

README.md
The original link referred to a notebook which is no longer in the docs/samples/client folder.
There are now 2 new notebooks. Hence I changed the link to use docs/samples/client
instead of referring to a specific notebook in the folder.
Also a space is removed on 2 lines at the end by my editor.
=> Update KFServing SDK Example link. Old link no longer exists

config/manager/manager.yaml, config/webhook/service.yaml
The webhook-server port in the manager Pod was set to 443, while it was
changed to 9443 [1]. Fix the discrepancy and refer to the port by name.
```release-note
Fix the webhook-server's port number in the manager Pod.
```
=> config: Fix port number of webhook in manager Pod

docs/samples/custom/torchserve/custom-server-with-external-storage.md, docs/samples/custom/torchserve/pv.yaml, docs/samples/custom/torchserve/pvc.yaml, docs/samples/custom/torchserve/pvpod.yaml, docs/samples/custom/torchserve/torchserve-custom-pv.yaml
Torchserve custom model server with external pv storage
Fixes #1179 
```
Add torchserve custom server with external pv storage
```
=> Feature: Add torchserve custom server with pv storage

hack/image_patch_dev.sh, pkg/agent/storage/s3.go, pkg/agent/syncer.go, pkg/agent/watcher.go, pkg/agent/watcher_test.go, pkg/apis/serving/v1beta1/predictor_triton.go
Model agent does not sync models from config when scaling to more replicas as there is no CREATE event generated when pods are started with initial mounted config.
Fixes #1203 
- Fix s3 uri parse issue when there is only bucket
- Force syncing the model config on startup, if we delete and recreate the pod, the agent should sync the model config and download/load the exiting models from model config.
```
{"level":"info","ts":1605267738.2322607,"logger":"modelAgent","msg":"Initializing model agent with","config-dir":"/mnt/configs","model-dir":"/mnt/models"} …
```
=> Sync from model config on agent startup

docs/OPENSHIFT_GUIDE.md, hack/quick_install.sh
These docs cover basic installation of KFServing on OpenShift.
Also changed the KFServing version in `quick_install.sh` to 0.4.1.
=> [Docs] Add OpenShift installation guide.

docs/samples/v1beta1/advanced/cluster_local.yaml, hack/quick_install.sh, pkg/apis/serving/v1beta1/openapi_generated.go, pkg/constants/constants.go, pkg/controller/v1alpha2/inferenceservice/resources/istio/virtualservice_test.go, pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go, test/scripts/run-e2e-tests.sh
Fixes #1218 
1. According to https://knative.dev/docs/serving/cluster-local-route/#label-a-service-to-be-cluster-local, the value should be `cluster-local`
2. Tested with the following example 
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
name: "sklearn-iris-local"
labels:
serving.knative.dev/visibility: cluster-local
spec:
predictor:
sklearn:
storageUri: "gs://kfserving-samples/models/sklearn/iris"
```
ksvc shows the correct local cluster url
```
kubectl get ksvc sklearn-iris-local-predictor-default
NAME …
```
=> Fix cluster local inference service

config/rbac/auth_proxy_service.yaml
This PR updates the control-plane label and selector for the `kfserving-controller-manager-metrics-service` to be consistent with the other control-plane values. This was an issue brought up in the manifests repo here: https://github.com/kubeflow/manifests/issues/1666
```release-note
Fix kfserving-controller-manager-metrics-service control-plane label and selector
```
=> Update metrics service label and selector

docs/samples/v1alpha2/onnx/mosaic-onnx.ipynb
The sample jupyter notebook for ONNX InferenceSerivce has a wrong link.
This PR fixes it.
=> Fix: Wrong link to README.md for ONNX InferenceService

docs/samples/v1alpha2/onnx/mosaic-onnx.ipynb
Closes #1256 
This PR fixes `mosaic-onnx.ipynb` to run seamlessly from the procedure in [README.md](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/onnx#run-a-sample-inference).
Also, I fixed the bugs on `mosaic-onnx.ipynb`.
The main fixed points are as follows.
* Use `INGRESS_HOST` and `INGRESS_PORT` instead of `CLUSTER_IP` that make us easy to work from the procedures in [README.md](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1alpha2/onnx#run-a-sample-inference).
* Change model name to `default` not to raise 500 error.
* c.f. https://github.com/microsoft/onnxruntime/issues/2442
* Change arguments of `image.resize` which does not match model's input shape.
=> Fix: mosaic-onnx sample for ONNX InferenceService

python/kfserving/README.md
The link to the sample for KFServing Python SDK is missing.
This PR fixes it.
=> Fix: Missing link to Python SDK samples

docs/apis/v1beta1/README.md, docs/samples/v1beta1/torchserve/autoscaling/README.md, docs/samples/v1beta1/torchserve/autoscaling/autoscaling.yaml, docs/samples/v1beta1/torchserve/bert/bert.yaml, docs/samples/v1beta1/torchserve/canary/README.md, docs/samples/v1beta1/torchserve/canary/canary.yaml, docs/samples/v1beta1/torchserve/gpu.yaml, docs/samples/v1beta1/torchserve/metrics/README.md, docs/samples/v1beta1/torchserve/metrics/metrics.yaml, docs/samples/v1beta1/torchserve/torchserve.yaml, docs/samples/v1beta1/torchserve/transformer.yaml, pkg/apis/serving/v1beta1/openapi_generated.go, pkg/apis/serving/v1beta1/predictor_torchserve.go, pkg/apis/serving/v1beta1/predictor_torchserve_test.go, pkg/apis/serving/v1beta1/swagger.json, test/e2e/predictor/test_torchserve.py
Fixes #
1. Use v2 protocolVersion to choose TorchServe implementation is confusing as v2 protocol is not supported yet, added the validation to reject when v2 protocol is specified.
2. Added the check that when `ModelClassName` is specified KFS choose the kfserver implementation otherwise use torchserve implementation.
```release-note
```
=> Use ModelClassName to differentiate kfserver or torchserve imp for v1 protocol

docs/samples/v1alpha2/onnx/mosaic-onnx.ipynb
Remove redundant code in ONNX InferenceService sample notebook.
Some modules are imported in multiple times.
=> Remove redundant code in ONNX InferenceService sample

cmd/agent/main.go, docs/samples/v1beta1/triton/multimodel/s3_secret.yaml, pkg/agent/downloader.go, pkg/agent/puller.go, pkg/agent/syncer.go, pkg/agent/watcher.go, pkg/agent/watcher_test.go, pkg/apis/serving/v1beta1/openapi_generated.go, pkg/constants/constants.go, pkg/webhook/admission/pod/agent_injector.go, pkg/webhook/admission/pod/agent_injector_test.go, test/e2e/predictor/test_torchserve.py
Fixes #1280 
tested loading new model and then unload
```
{"level":"info","ts":"2021-01-07T03:40:55.638Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
{"level":"info","ts":"2021-01-07T03:40:55.638Z","caller":"logging/config.go:111","msg":"Logging level set to: info"}
{"level":"info","ts":"2021-01-07T03:40:55.638Z","caller":"logging/config.go:78","msg":"Fetch GitHub commit ID from kodata failed","error":"open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":"2021-01-07T03:40:55.638Z","caller":"agent/main.go:234"," …
```
=> Fix model puller flag and logging conflicts

docs/samples/metrics-and-monitoring/README.md, docs/samples/metrics-and-monitoring/prometheus/clusterrolebinding.yaml
The sample instructions for getting started with metrics monitoring for KFServing models (see [here](https://github.com/kubeflow/kfserving/tree/master/docs/samples/metrics-and-monitoring)) triggers a bug in Kustomize.
The Kustomize bug is reported here: https://github.com/kubernetes-sigs/kustomize/issues/3430
Meanwhile, this simple one-field change in the kustomization resources provides a workaround which enables Prometheus monitoring to work as claimed.
@Tomcli @animeshsingh 
This is a pure documentation PR.
```release-note
NONE
```
=> Workaround for kustomize bug triggered in metrics and monitoring instructions

test/workflows/components/workflows.libsonnet
Transformer example is moved to v1alpha2 folder, need to fix the path for the image build step.
Fixes #
```release-note
```
=> Fix transformer image build path

pkg/apis/serving/v1alpha2/inferenceservice_conversion.go, pkg/apis/serving/v1alpha2/inferenceservice_conversion_test.go
Fixes #1310 
1. Add nil check in converter for explainer that doesn't support v1alpha2 spec.
```release-note
```
=> Add nil conversion for v1beta1 -> v1alpha2 explainer spec

python/kfserving/kfserving/api/kf_serving_client.py, test/e2e/predictor/test_multi_model_serving.py
Add integration tests for MMS when using the V2 protocol with SKLearn and XGBoost models.
Fixes #
There are some changes due to `black`'s autoformatting rules. 
```release-note
NONE
```
=> Add E2E tests for MMS with the V2 protocol

docs/predict-api/v2/rest_predict_v2.yaml
Adds the OpenAPI spec for the V2 dataplane (already in use in https://github.com/SeldonIO/MLServer/blob/master/openapi/dataplane.yaml).
Fixes #
```release-note
NONE
```
=> Add OpenAPI schema for V2 dataplane

python/aixexplainer/setup.py, python/lgbserver/setup.py, test/scripts/run-e2e-tests.sh
The latest numpy 1.20.0 release breaks the aix and lightgbm python servers
Fixes #1335 
```release-note
```
=> Fix dependency for lightgbm and aix python server

Makefile
Make the port optional in custom spec for predictor/transformer/explainer
Fixes #1350
=> Make port optional in custom spec

pkg/apis/serving/v1beta1/predictor_onnxruntime.go, pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go
Allow any model file name with `.onnx` extension or a storageURI with no extension.
This was added in `v1alpha2` but was not ported to `v1beta1` https://github.com/kubeflow/kfserving/pull/1078
=> Allow any .onnx file name in v1beta1 api

config/configmap/inferenceservice.yaml, docs/MULTIMODELSERVING_GUIDE.md, docs/samples/v1beta1/sklearn/multimodel/README.md, docs/samples/v1beta1/triton/multimodel/README.md, install/v0.5.0/kfserving.yaml, install/v0.5.0/kfserving_crds.yaml
**What this PR does / why we need it**: By default the flags in inferenceservice.yaml for SKLearn, XGBoost, LightGMB, and Triton have been set to true which means MMS is enabled without users knowing. We want to prevent this from happening.
Fixes #
```release-note
Using MMS requires flags to be set in inferenceservice.yaml
```
=> Prevent experimental features from being set by default setting multimodelserver flags to false 

pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go, test/e2e/common/utils.py, test/e2e/predictor/test_lightgbm.py, test/e2e/transformer/test_transformer.py
The latest routing tag adds extra prefix "latest" to the routing host which causes the domain name exceeding the max 63 char length for some of the existing inference services with long name.
Fixes #1377 
```release-note
latest tag url is removed.
```
=> Remove unnecessary "latest" routing tag

pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
InferenceService expose an option to customise the istio local gateway that is used with them, however the reconviler still points to the hard coded local gateway specified in constants. This fixes that by using the local gateway from config instead.
Fixes #1383
```release-note
```
=> Use custom local gateway for isvc external service

docs/samples/storage/uri/README.md, pkg/credentials/https/https_secret.go, pkg/credentials/https/https_secret_test.go, pkg/credentials/service_account_credentials.go, python/kfserving/kfserving/storage.py
**What this PR does / why we need it**:  Currently there is no header support for inference service uri request. It would be beneficial as authentication for requests may require credentials to be passed into the header.
Fixes #1351
```release-note
```
=> Feature to include headers in http/https service requests (non-MMS)

Makefile, README.md, test/scripts/run-e2e-tests.sh
Based off  https://github.com/kubeflow/kfserving/blob/master/test/scripts/create-cluster.sh#L31 , the test cluster uses Kubernetes 1.17.
This PR updates the `kubectl` version used to a matching version. This version also has the fix for the problem outlined in this issue: https://github.com/kubernetes/kubernetes/issues/91615 where re-applying a CRD with deeply nested properties took a long time. 
This PR also changes the README instructions to tell users to use a version of `kubectl` which has a fix for the above issue.
=> Update kubectl version used in e2e tests

pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
This PR is to patch Inferenceservice annotations/labels to the kfserving routing VirtualService. It is already patched in [v1alpha2](https://github.com/kubeflow/kfserving/blob/master/pkg/controller/v1alpha2/inferenceservice/resources/istio/virtualservice.go#L276-L277).
**Which issue(s) this PR fixes** *(optional, in `fixes #1406 (, fixes #1406 , ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubeflow/kfserving/issues/1406
```release-note
```
=> patch inferenceservice annotations to kfserving routing virtualservice

pkg/apis/serving/v1alpha1/trained_model_status.go, pkg/controller/v1alpha1/trainedmodel/controller.go, pkg/controller/v1alpha1/trainedmodel/controller_test.go
**What this PR does / why we need it**: Prevents the trained model from being deployed if the inference service is not ready
Fixes #
**Special notes for your reviewer**: I plan on adding a few other validation checks in controllerafter this PR
```release-note
None
```
=> Validate the parent inference service is ready in trained model controller

pkg/agent/storage/provider.go, pkg/apis/serving/v1alpha1/trainedmodel_webhook.go, pkg/apis/serving/v1alpha1/trainedmodel_webhook_test.go, pkg/apis/serving/v1beta1/component.go
**What this PR does / why we need it**: The webbook will validate the storageURI passed in the trained model
Fixes #
```release-note
None
```
=> Validation for storage uri in webhook

pkg/controller/v1alpha1/trainedmodel/suite_test.go
**What this PR does / why we need it**:  Test suite did not define recorder. Lead to invalid memory access when trying to use Event() and Eventf() functions.
Fixes #
```release-note
None
```
=> Defined recorder in test suite

.github/workflows/alibiexplainer-docker-publish.yml, .github/workflows/artexplainer-docker-publish.yml, config/configmap/inferenceservice.yaml, install/v0.5.1/kfserving.yaml
We no longer have permission for gcr.io project and not able to take actions in case release builds are timed out, so we have to migrate off gcr.io. There are other images we need to migrate off as well, will create a separate issue.
Fixes #1426 
```release-note
```
=> Migrate alibi image from gcr.io to docker hub

README.md
There was broken formatting in the note about certain fields needing Knative 0.17+. Fixed the formatting and updated the note with a bit more info.
=> Update and fix link in README regarding podspec

config/overlays/test/configmap/inferenceservice.yaml, docs/DEVELOPER_GUIDE.md, pkg/apis/serving/v1alpha1/trained_model_status.go, pkg/apis/serving/v1beta1/configmap.go, pkg/apis/serving/v1beta1/predictor.go, pkg/apis/serving/v1beta1/predictor_custom.go, pkg/apis/serving/v1beta1/predictor_custom_test.go, pkg/apis/serving/v1beta1/predictor_lightgbm.go, pkg/apis/serving/v1beta1/predictor_lightgbm_test.go, pkg/apis/serving/v1beta1/predictor_onnxruntime.go, pkg/apis/serving/v1beta1/predictor_onnxruntime_test.go, pkg/apis/serving/v1beta1/predictor_pmml.go, pkg/apis/serving/v1beta1/predictor_pmml_test.go, pkg/apis/serving/v1beta1/predictor_sklearn.go, pkg/apis/serving/v1beta1/predictor_sklearn_test.go, pkg/apis/serving/v1beta1/predictor_tfserving.go, pkg/apis/serving/v1beta1/predictor_tfserving_test.go, pkg/apis/serving/v1beta1/predictor_torchserve.go, pkg/apis/serving/v1beta1/predictor_torchserve_test.go, pkg/apis/serving/v1beta1/predictor_triton.go, pkg/apis/serving/v1beta1/predictor_triton_test.go, pkg/apis/serving/v1beta1/predictor_xgboost.go, pkg/apis/serving/v1beta1/predictor_xgboost_test.go, pkg/controller/v1alpha1/trainedmodel/controller.go, pkg/controller/v1alpha1/trainedmodel/controller_test.go
**What this PR does / why we need it**: We need to verify the framework based on the model server. Should reject if the framework does not. Logs the condition of the trained model (FrameworkSupported) when reconciling.
Fixes #1422 
```release-note
None
```
=> Added validation for framework in the trained model controller

docs/samples/v1alpha2/sklearn/README.md, docs/samples/v1beta1/sklearn/v1/README.md
SKLearn Server links point to `page not found`. Fixed links to point to the correct `README` file. Easy navigation and easy reading for others.
=> Fix broken links to SKLearn Server README

hack/generate-install.sh, install/v0.5.1/kfserving_kubeflow.yaml
Using the kubeflow overlay, I generated an install yaml file for the v0.5.1 release. This was done from the 0.5-release branch with the overlay copied over. Tags were updated to `v0.5.1` from `latest` where applicable and the alibi-explainer image was switched to docker hub like in `v0.5.1/kfserving.yaml`.
This will be useful for people trying to install the latest KFServing into their Kubeflow environments.
=> Add kubeflow install yaml for v0.5.1

README.md
Updates the link to the InferneceService configmap
=> Fix link to inferenceservice configmap

docs/samples/v1beta1/pmml/README.md, pkg/apis/serving/v1beta1/component.go, pkg/apis/serving/v1beta1/inference_service_validation_test.go, pkg/apis/serving/v1beta1/predictor_pmml.go, pkg/apis/serving/v1beta1/predictor_pmml_test.go, python/pmml.Dockerfile, python/pmmlserver/pmmlserver/model.py, python/pmmlserver/pmmlserver/test_model.py, python/pmmlserver/setup.py, test/e2e/predictor/test_pmml.py
This pull-request is to improve the PMMLServer predict performance.
1. Replace [pypmml](https://github.com/autodeployai/pypmml) to [jpmml-evaluator-python](https://github.com/jpmml/jpmml-evaluator-python)
2. Improve the documentation of PMMLServer.
3. Humanize PMML Predict results.
Why change it? I've deployed a **large size** PMML model on KFServing but it slowly. I will be going to figure out this problem.
Fixes #
The following code is a huger PMML model generator.
[https://gist.github.com/AnyISalIn/b88399849966228e2ceedb57c3b6c8b9](https://gist.github.com/A …
=> Improve PMMLServer predict performance

config/configmap/inferenceservice.yaml, config/default/manager_image_patch.yaml
This PR pins the image tags to `v0.5.1` in the config YAMLs. This way `kubeflow/manifests` can use the config directory from this PR's commit.
Related: https://github.com/kubeflow/kfserving/issues/1461
=> Pin image tags in release-0.5 branch

python/kfserving/kfserving/storage.py, python/kfserving/test/test_storage.py
To fix the bug that storage initializer fails to download *.tar.gz and *.zip from uri with query params.
Changes made,
1. change ```Storage._download_from_uri``` to use path part of the uri without query params to guess mime types
Fixes #1462
```release-note
Fix storage initializer fails to download tar.gz and zip from uri with query params
```
=> Fix storage initializer fails to download tar.gz and zip from uri with query params

pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go, pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go
With the latest knative version it always generates two similar looking revisions when initial inference service is created, the root cause looks like is related to the fact in inference service controller it always update the knative service immediately after that is created, the reconciliation generates a diff between created knative service and desired knative service as knative mutating webhook defaults the `enableServiceLink` to false.
Fixes #1467  …
=> Resolve knative service diff to prevent dup revision

docs/PRESENTATIONS.md
Documentation change only. 
Add link to Youtube recording of "Serverless Machine Learning Inference with KFServing - Clive Cox, Seldon & Yuzhui Liu, Bloomberg" from Serverless Practitioners Summit Europe 2020
**Release notes**
```release-note
NONE
```
=> Add Serverless Practitioners Summit 2020 Presentation

config/overlays/kubeflow/cluster-role.yaml, config/overlays/kubeflow/kustomization.yaml, config/overlays/kubeflow/namespace-patch.yaml, config/overlays/kubeflow/statefulset-patch.yaml
I realized that the kubeflow overlay was not in the release-0.5 branch, so a commit from this branch wouldn't be useable in kubeflow/manifests. This PR cherry-picks the overlay commit.
/cc @yuzisun @animeshsingh
=> Cherry-pick of 'Update kubeflow overlay (#1424)' into release-0.5

docs/samples/metrics-and-monitoring/prometheus-operator/namespace.yaml
Right now the created namespace will get a `kfserving-` prefix which will create a namespace called `kfserving-kfserving-monitoring`.
This will make subsequent object creations to fail since they will be meant for the `kfserving-monitoring` namespace.
Here's the result of running `kustomize build docs/samples/metrics-and-monitoring/prometheus-operator | k apply -f -`, as the instructions suggest https://github.com/kubeflow/kfserving/blob/master/docs/samples/metrics-and-monitoring/README.md#install-prometheus
```bash
namespace/kfserving-kfserving-monitoring created
customresourcedefinition.apiextensions.k8s.io/alertmanagerconfigs.monitoring.coreos.com created
customresourcedefinition.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com created …
```
=> Fix wrong name for kfserving-monitoring namespace

test/scripts/run-e2e-tests.sh
Add a wait condition for the cert-manager installation on e2e test. reference #1470
=> add wait condition for cert-manager webhook

pkg/apis/serving/v1beta1/component.go, pkg/apis/serving/v1beta1/predictor_custom.go, pkg/apis/serving/v1beta1/predictor_custom_test.go, pkg/constants/constants.go
* Allows custom predictor to set protocol. This will allow correct URI to be exposed in status.
Fixes #1482
=> Allow custom predictor to set protocol

docs/samples/pipelines/README.md, docs/samples/pipelines/kfs-pipeline-v1alpha2.ipynb, docs/samples/pipelines/kfs-pipeline.ipynb, docs/samples/pipelines/sample-custom-model.py
An example using the v1alpha2-based component was re-added for those who have not updated to the latest KFServing yet.
Left a note in the README about the example for those not on a KFServing version >= v0.5.0.
=> Update pipelines documentation

cmd/agent/main.go, docs/samples/batcher/basic/batcher_v1beta1.yaml, go.mod, pkg/agent/watcher.go, pkg/batcher/handler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go, pkg/webhook/admission/pod/agent_injector.go, pkg/webhook/admission/pod/agent_injector_test.go
Fixes #1041 
1. Use sflag instead and fix usages
2. Poll user container health before starting the agent as model puller calls load/unload endpoint when syncing the model config on startup
3. Add readiness probe for MMS
4. Fix ko-app issue in development mode #1435 
```release-note
```
=> Add readiness check to model agent

pkg/apis/serving/v1alpha1/trained_model.go, pkg/apis/serving/v1alpha1/trained_model_status.go, pkg/constants/constants.go, pkg/controller/v1alpha1/trainedmodel/controller.go, pkg/controller/v1alpha1/trainedmodel/controller_test.go, pkg/controller/v1beta1/inferenceservice/utils/utils.go, pkg/controller/v1beta1/inferenceservice/utils/utils_test.go, test/e2e/predictor/test_multi_model_serving.py
**What this PR does / why we need it**: Checks to see if the inference service has enough memory resources for all children trained models. Will reject child that asks for more resources than parent can provide.
Fixes #
```release-note
None
```
=> Validate trained model memory based on parent inference service

python/xgbserver/setup.py, python/xgbserver/xgbserver/model.py
Due to https://github.com/dmlc/xgboost/pull/3970 , prediction calculated by current xgboost model is incorrect for some cases. The result deviates quite significantly compared to training set. 
Fix incorrect prediction result in xgboost server.
- Additional dependency (numpy) is added to xgboost server
```release-note
```
=> [xgboostserver] Convert list input to numpy array before creating DMatrix

cmd/agent/main.go, pkg/agent/puller.go, pkg/agent/watcher.go, pkg/agent/watcher_test.go
Makes sure models are downloaded before starting the watcher for the model agent. 
Fixes #1338
**Manual Test**
These changes were run locally and checked by looking at the agent container logs on the predictor pod. Once the train models were deployed, I checked the logs for the agent and made sure that all models were downloaded before the watcher was started, which the logs confirmed.
```
{"level":"info","ts":"2021-03-21T17:21:22.764Z","caller":"logging/config.go:110","msg":"Successfully created the logger."}
{"level":"info","ts":"2021-03-21T17:21:22.765Z","caller":"logging/config.go:111","msg": …
```
=> Watcher should not be started until models downloaded in MMS

pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go
Reconcile ingress routing virtualservice when annotations/labels are updated
Fixes #1524 
```release-note
```
=> reconcile ingress routing virtualservice when annotations/labels are updated

docs/samples/logger/basic/README.md, docs/samples/logger/basic/logger_demo.ipynb, docs/samples/logger/basic/message-dumper.yaml, docs/samples/logger/basic/sklearn-logging.yaml, docs/samples/logger/knative-eventing/README.md, docs/samples/logger/knative-eventing/broker.yaml, docs/samples/logger/knative-eventing/logger_demo.ipynb, docs/samples/logger/knative-eventing/message-dumper.yaml, docs/samples/logger/knative-eventing/sklearn-logging.yaml, docs/samples/logger/knative-eventing/trigger.yaml
The logger samples were updated to be able to work with newer Knative Eventing versions, and InferenceService YAMLs were also updated to use the v1beta1 API.
=> Update logger samples for newer eventing versions

python/kfserving/kfserving/storage.py, python/kfserving/requirements.txt, python/kfserving/test/test_s3_storage.py, python/kfserving/test/test_storage.py
Uses the boto3 library instead of minio for storage-initializer, mainly in order to allow use of IAM Roles for Service Accounts for AWS users, also changes storage tests to mock boto3 instead of minio
Fixes #831
Cherrypicks the first commit from https://github.com/kubeflow/kfserving/pull/1130 since there doesn't seem to be much continuing activity there
I've also tested this by building/pushing the new image to an ECR registry, changing the image location in the inference config map, and using service accounts both with secret credentials, and IAM roles.
1. …
=> Change storage-init to use boto3

pkg/apis/serving/v1alpha1/trained_model_status.go, pkg/apis/serving/v1beta1/predictor.go, pkg/controller/v1alpha1/trainedmodel/controller.go, pkg/controller/v1alpha1/trainedmodel/controller_test.go
**What this PR does / why we need it**: Trained Model requires the parent inference service to enable multi-model serving. This PR adds a condition to let users know that their model is not Ready if parent's predictor is not configured to mms.
Fixes #
```release-note
```
=> Adds condition for Trained Model to check if isvc predictor supports MMS

pkg/agent/watcher_test.go, pkg/apis/serving/v1beta1/predictor_custom.go, pkg/logger/handler.go, pkg/logger/handler_test.go, pkg/logger/worker.go
There is a regression to propagate the error response when we consolidate the logger to the agent.
Fixes #1530 
```release-note
```
=> Fix logger for error response case

web-app/frontend/src/app/pages/server-info/server-info.component.ts
Makes the app's logic for detecting Grafana more robust. Instead of only relying on whether the request failed or the UI should also check if the response is formatted as expected.
This will mitigate the current issue where, in Kubeflow, the Central Dashboard will be returning its own `index.html` for non-matched routes. The Central Dashboard also listens to the root URL `/` and that's why it will return a response for the `/grafana` endpoint as well.
Fixes #1540
In order to test the changes you will have to deploy the app from it's manifests:
1. Checkout the …
=> fix(web-app): Fix Grafana detection due to HEAD request

docs/samples/v1beta1/sklearn/v1/README.md
This PR fixes a broken link the sklearn-iris sample README that points to the ingress info in the main README.
=> Fix broken link to ingress info in README

pkg/agent/storage/gcs.go, pkg/agent/storage/s3.go, pkg/agent/watcher_test.go
**What this PR does / why we need it**: The model directory will be converted into a file whenever the fileName (Model dir, model name, objectName) is equal to the model directory. This will prevent that override from happening.
Fixes #
```release-note
```
=> Prevents /mnt/models/<model name> from being converted into a file

docs/samples/storage/s3/README.md, docs/samples/storage/s3/s3_secret.yaml, pkg/agent/storage/utils.go, pkg/credentials/s3/s3_secret.go, pkg/credentials/s3/s3_secret_test.go
**What this PR does / why we need it**: Adds option to use anonymous credentials for s3 to access public buckets
Fixes #
```release-note
None
```
=> Added annotation to use anonymous credentials for s3

hack/violation_exceptions.list
Accept violation of PredictorConfig.SupportedFrameworks' list type (introduced by #1413) to fix the openapi generator error
Fixes #1565
=> accept configmap violation

hack/quick_install.sh
Also updated the script to use KFServing v0.5.1.
`addOnComponents` is now deprecated, so this section was removed from the IstioOperator definition.
Tested this on K8s 1.18 on Minikube and OpenShift 4.6
=> Update quick install to use Istio 1.9.0

docs/DEVELOPER_GUIDE.md
**What this PR does / why we need it**: The current go version requirement is 1.13+ but I need version 1.14 to run `make deploy-dev`. Updating doc so others won't run into this issue.
Fixes #1585 
```release-note
```
=> Update Go version requirement in developer's guide

web-app/frontend/package.json
Makes the `APP_PREFIX` env var to properly configure the prefix of the app. The script tags will be using relative urls so the browser will be appending the prefix found from the `<base href=...">` element.
Fixes #1572 
You can try out this PR by following the steps to expose the app locally from #1571 
cc @yuzisun
/cc @tasos-ale @pvaneck
=> mwa(front): Don't hardcode the base-url

docs/predict-api/v2/rest_predict_v2.yaml
The item definition of #/components/schemas/tensor_data was invalid anyOf syntax. It now correctly validates with https://apitools.dev/swagger-parser/online/
```release-note
Fixes: rest_predict_v2.yaml now correctly validates
```
=> [Predict Protocol V2] Fix rest_predict_v2.yaml definition

test/e2e/explainer/test_tabular_explainer.py
This should hopefully reduce the number of timeout failures during CI.
Closes: #1594
/cc @yuzisun
=> Increase timeout for tabular explainer e2e test

docs/samples/v1beta1/transformer/torchserve_image_transformer/README.md, python/kfserving/kfserving/kfmodel.py
Fix a couple of typos
* explainer_url to use explainer_host insteand predictor_host in
the default/base explain handler
* yaml file name in readme for the transformer sample
Signed-off-by: Chin Huang <chhuang@us.ibm.com>
Fixes #
```release-note
```
=> Fix explainer_url to use explainer_host

pkg/controller/v1beta1/inferenceservice/components/component.go, pkg/controller/v1beta1/inferenceservice/components/explainer.go, pkg/controller/v1beta1/inferenceservice/components/predictor.go, pkg/controller/v1beta1/inferenceservice/components/transformer.go
Adds the logging functionality in explainer, by adding annotations for logger in the reconciler of the explainer, similarly to the predictor logger.
Fixes #1404
Test results:
```
$ curl -H 'Host: german-credit.default.example.com' -H 'Content-type: application/json' -d@./input.json http://172.18.255.200/v1/models/german-credit:explain 
{"predictions": [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, …
```
=> add logger in explainer and transformer

hack/self-signed-ca.sh
After run self-signed-ca.sh instead using cert-manager and apply the sample InferenceService yaml, there is certificate-signed-by-unknown-authority error. this is because the self-signed-ca scripts misses some webhook patches for 0.6.0-rc0 release.
=> fix certificate unknown authority error using self-sign-ca scripts

docs/samples/v1beta1/sklearn/v2/README.md
The url to the V2 dataplane in [this doc](https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/sklearn/v2) point to this outdated url https://github.com/kubeflow/kfserving/blob/master/docs/samples/predict-api/v2
Change to https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2
Fixes #1634 
```release-note
```
=> Fix broken url

pkg/controller/v1beta1/inferenceservice/controller_test.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler.go, pkg/controller/v1beta1/inferenceservice/reconcilers/ingress/ingress_reconciler_test.go
Signed-off-by: Theofilos Papapanagiotou <theofilos@gmail.com>
Makes the ingress reconciler compatible with Istio 1.10.
By moving the host header rewrite of the main istio virtualservice from the HTTPRouteDestination to the HTTPRoute.
Fixes #1643
```release-note
Support for Istio 1.10
```
=> ingress reconciler compability with istio 1.10

README.md, docs/samples/metrics-and-monitoring/README.md
This PR fixes a documentation bug in KFServing (outdated links to Iter8)
Fixes #1631 
```release-note
Links to Iter8 extensions that support live experiments and progressive delivery for KFServing models
```
=> Corrected links to Iter8 KFServing extensions

cmd/agent/main.go, pkg/logger/handler.go, pkg/logger/handler_test.go, pkg/logger/types.go, pkg/logger/worker.go, pkg/webhook/admission/pod/agent_injector.go, pkg/webhook/admission/pod/agent_injector_test.go
Signed-off-by: Theofilos Papapanagiotou <theofilos@gmail.com>
Adds the `component` label (predictor, transformer, explainer) in the cloudevent extension so we can tell the source of the payload logging event.
This is a follow-up on #1597
Two example cloudevent inference requests, one as seen in the `component: transformer` with the base64 payload and one as seen in the `component: predictor` with the npy array as a list in json:
```
☁️  cloudevents.Event
Validation: valid
Context Attributes,
specversion: 1.0
type: org.kubeflow.serving.inference.request
source: http://localhost:9081/
id: 9e4163ad-f543-427e-bfed-5a122cf41bab
time: 2021-05-29T22:23:58.461696863Z
datacontenttype: application/json
Extensions, …
```
=> add the component label in payload logging

hack/self-signed-ca.sh
On my testing environment (debian 11, openssl 1.1.1k, minikube with k8s 1.20,
go 1.15, kfserving 0.5) I get some TLS errors when testing kfserving,
namely
"x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching"
when trying to deploy a simple InferenceService resource.
After some digging I found this problem:
```
openssl req -noout -text -in server.csr | grep "Subject Alternative Name" -A 1
X509v3 Subject Alternative Name:
DNS:kfserving-webhook-server-service, DNS:kfserving-webhook-server-service.kfserving-system, DNS:kfserving-webhook-server-service.kfserving-system.svc, DNS:kfserving-webhook-server-service.kfserving-system.svc.cluster, DNS:kfserving-webhook-server-service.kfserving-system.svc.cluster.local
openssl x509 -in server.crt …
```
=> Improvements to self-signed-ca.sh

docs/DEVELOPER_GUIDE.md
It should be `docker.io/<username>` and you use this throughout the rest
of the doc. One example mistypes `docker.io/<username>/[project]`.
**What this PR does / why we need it**: See above.
```release-note
None
```
=> Fix an example on KO_DOCKER_REPO in the dev guide

docs/samples/kafka/README.md
#1679
knative/eventing-contrib as archived.
Some folders were moved to knative-sandbox/eventing-kafka
https://github.com/knative-sandbox/eventing-kafka/pull/53
So I have updated the links accordingly.
=> Updated Kafka event source url in samples

python/kfserving/kfserving/kfserver.py, python/kfserving/kfserving/utils/utils.py, python/kfserving/requirements.txt
For linux platforms, infer cpu-limit for the container from 'cfs_quota_us'
and 'cfs_quota_us' files. Use min(32, cpu_count + 4) to limit number of
max asyncio workers. Refer https://bugs.python.org/issue35279 for formula
source.
Python (and asyncio) is not container aware and thus ends up creating
asyncio workers proportional to cpu core count of the machine and not the
container. This spawns too many asyncio workers on high cpu core machines
running containers with low cpu-limit causing throttling.
Fixes #1690 
1. Please confirm that if this PR changes any …
=> Limit number of asyncio workers in custom transformers

python/sklearnserver/sklearnserver/__main__.py
Runing:
``` bash
make test 
```
in sklearnserver returns: 
```
sklearnserver/__main__.py:37: error: Incompatible types in assignment (expression has type "TracebackType", variable has type "List[str]")
sklearnserver/__main__.py:37: error: Incompatible types in assignment (expression has type "None", variable has type "List[str]")
Found 2 errors in 1 file (checked 6 source files)
```
due to mypy check failing the test, this PR fixes the issue. 
Fixes # …
=> feat(bug): fix broken mypy test

docs/samples/explanation/aix/mnist/rfserver/rf.Dockerfile, docs/samples/explanation/art/mnist/sklearnserver/sklearn.Dockerfile, docs/samples/kafka/transformer.Dockerfile, docs/samples/v1alpha2/custom/customized-urls/Dockerfile, docs/samples/v1alpha2/transformer/image_transformer/transformer.Dockerfile, docs/samples/v1alpha2/triton/bert/bert_tokenizer/Dockerfile, docs/samples/v1beta1/transformer/torchserve_image_transformer/transformer.Dockerfile, docs/samples/v1beta1/triton/bert/bert_tokenizer_v2/Dockerfile, docs/samples/v1beta1/triton/torchscript/transformer.Dockerfile, python/aiffairness.Dockerfile, python/aixexplainer.Dockerfile, python/alibiexplainer.Dockerfile, python/artexplainer.Dockerfile, python/lgb.Dockerfile, python/pmml.Dockerfile, python/pytorch-gpu.Dockerfile, python/pytorch.Dockerfile, python/sklearn.Dockerfile, python/storage-initializer.Dockerfile, python/xgb.Dockerfile
See the rationale at https://github.com/hadolint/hadolint/wiki/DL3042
In addition to space saving, it also ensures that pip doesn't install
from local cache (especially in case of a rebuild) and reduces the
chance of creating bugs during development.
**What this PR does / why we need it**: See above
**Special notes for your reviewer**: It's difficult for me to test every image, but they shouldn't make functional changes to the built Docker images for clean build.
```release-note
Use `pip install --no-cache-dir` instead of naked `pip install` in Dockerfiles.
```
=> Append "--no-cache-dir" to "pip install" in Dockerfiles

pkg/utils/utils.go
`range` copies the elements by value. Avoid using it when searching for
volumes. This should potentially improve overall performance when
`AppendVolumeIfNotExists` is used.
**What this PR does / why we need it**: above
```release-note
Performance improvements for AppendVolumeIfNotExists.
```
=> Use index instead of element when searching for a volume

pkg/controller/v1alpha1/trainedmodel/controller.go, pkg/controller/v1beta1/inferenceservice/controller.go, pkg/utils/utils.go
They achieve exactly the same functionality.
**What this PR does / why we need it**: Above
Fixes #
```release-note
None
```
=> `ContainsString` and `Includes` utils are duplicates

docs/samples/v1beta1/tensorflow/canary.yaml
The canary should have the same name as the base tensorflow.yaml so it correctly applies as a canary
=> Make canary name match tensorflow.yaml

python/sklearnserver/sklearnserver/model.py, python/sklearnserver/sklearnserver/test_model.py
Similar to the safeguard that exists in pytorchserver.
**What this PR does / why we need it**: It'll be more robust and better guard against inadvertent error (which may take a long time to debug out)
```release-note
sklearnserver now errors out when multiple model files or no model file are present
```
=> sklearnserver: add safeguard if multiple model files are present

.gitignore
Add the istio directory which is downloaded by `quick_install.sh` to the ignore list
=> Ignore istio dir downloaded by hack install

config/configmap/inferenceservice.yaml, config/default/manager_image_patch.yaml, config/web-app/deployment.yaml
Note this is a PR into the release-0.6 branch and **not** master.
In preparation for using KFServing v0.6.0 in the next Kubeflow manifests 1.4 release, the image tags need to be pinned. This PR pins the image tags to v0.6.0 in the config YAMLs. This way kubeflow/manifests can use the config directory from this PR's commit.
This is similar to what we did in v0.5.1 (https://github.com/kubeflow/kfserving/pull/1465).
Note: I could not find an image tag for `v0.6.0-gpu` for  [`gcr.io/kfserving/pytorchserver`](https://console.cloud.google.com/gcr/images/kfserving/GLOBAL/pytorchserver), so I left it at `latest-gpu` as that is around the same time that v0.6.0 was tagged.
Ref: https://github.com/kubeflow/manifests/issues/1960
=> Pin image tags in release-0.6 branch

pkg/agent/storage/gcs.go, pkg/agent/storage/s3.go
If a model is stored in a bucket in the format 
```
models/modelname/1/model.onnx
```
ListObjects API with the prefix `models/modelname/`  will return the below keys incase of s3
```
models/modelname/
models/modelname/1/
models/modelname/1/model.onnx
```
whereas in case of GCS it would return 
```
models/modelname/1/model.onnx
```
Incase of s3, the nested directories get's created as file inside the model directory /mnt/models. This fix will prevent that from happening. 
Fixes #1769 
1. Please confirm that if this PR changes any image versions, then that's …
=> prevent nested directories in s3 to be created as file inside model directory /mnt/models

python/kfserving/kfserving/kfserver.py, python/kfserving/requirements.txt, python/kfserving/setup.py
`kfserving` currently cannot be installed on python versions >3.7 due to a hard dependency on `ray[serve]==1.3.0` which itself requires `python==3.7`. 
This PR updates the pinned `ray` version to `1.5.0` which does support newer python versions, and makes the necessary API changes. 
Fixes #1753 
```release-note
Adds python3.9 support to KFServing.
```
=> Upgrade ray[serve] to version 1.5.0, allowing kfserving to be installed on python3.9

python/custom_model/model_remote.py, python/kfserving/kfserving/kfserver.py
Fixes a bug in previous https://github.com/kubeflow/kfserving/pull/1772, need to replace `issubclass` to `isinstance` after changing to ray 1.5.
```release-note
```
=> Fix parallel inference example with Ray 1.5

pkg/credentials/s3/s3_secret.go, python/kfserving/kfserving/api/creds_utils.py
The boto3 package seems to look for AWS_DEFAULT_REGION, meanwhile
kfserving uses AWS_REGION, that doesn't seem to be working
(tested following
https://github.com/kubeflow/kfserving/blob/master/docs/samples/storage/s3/README.md).
This change doesn't replace all occurrences of AWS_REGION, but only
the ones that set the environment variables.
GH-1765
Add also the possibility to force boto to use a custom CA Bundle path when validating the TLS certificate of the S3 endpoint. Our use case is related to using an internal S3 endpoint (based on Openstack Swift) offering a TLS certificate signed by our internal CA.
GH-1766
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
=> Fix AWS_REGION and add AWS_CA_BUNDLE to s3_secrets.go

docs/samples/v1beta1/transformer/feast/README.md, docs/samples/v1beta1/transformer/feast/driver_transformer.Dockerfile, docs/samples/v1beta1/transformer/feast/driver_transformer.yaml, docs/samples/v1beta1/transformer/feast/driver_transformer/__main__.py, docs/samples/v1beta1/transformer/feast/driver_transformer/driver_transformer.py, docs/samples/v1beta1/transformer/feast/setup.py
Made the following changes for Feast transformer to support the
latest Feast v0.12.1
1. Change the python client API to rest API
2. Use the new Feast feature server
3. Use python 3.8
4. Update sample outputs in doc
Fixes #
```release-note
```
=> Upgrade Feast transformer for v0.12.1
